### ISSUE TITLE
Feature request: Direct Upload to "Velo Hero"

### ISSUE THREAD

**Issue by Scooty66** [Sublimis/UrbanBiker#101]
Hi there,

great app, really enjoy using it.

Maybe you would like to consider to integrate an upload function to "[Velo Hero](https://www.velohero.com/)", similar to "Strava" or "Google Fit"?
"[Velo Hero](https://www.velohero.com/)" is a site to log and more importantly further analyse your recorded tracks.

Currently I am uploading my UrbanBiker tracks via Share tracks/GPX only/using an e-mail app to a personalised "Velo Hero" mail address (provided by "Velo Hero"). So some clicks to do.

More convenient (and quicker) would be to offer upload to "Velo Hero" like for "Strava" or "Google Fit".

I suppose easiest for implementation in UrbanBiker could be to generate an e-mail with a GPX-file attachment (see [https://www.velohero.com/help/email-import.html](https://www.velohero.com/help/email-import.html)) to an account configurable in UrbanBiker's menu Settings/Accounts. 
But there might be a direct upload API as apps like "IpBike"/"BikeComputer"/etc already support direct upload (see [https://www.velohero.com/help/smartphone-apps.html](https://www.velohero.com/help/smartphone-apps.html))?

Thanks for consideration,
Andreas

NB:
I am not affiliated with the "Velo Hero" website/service, just a very satisfied user.

**Comment by zett42** [comment]
> I suppose easiest for implementation in UrbanBiker could be to generate an e-mail with a GPX-file attachment

... which fails when the GPX file is larger than the limit of the email provider. This is why I also support this feature request.

> But there might be a direct upload API

There is an API, but it is not public. You have to [ask the developer](https://www.velohero.com/help/faq.html#is-there-an-api-for-developers).

**Comment by Sublimis** [comment]
Hi, it seems this could be possible to implement without involving e-mails, if we can get in touch with the developer to describe their API to us. Please allow us a few weeks for this. Thanks for the feedback!

**Comment by Sublimis** [comment]
This can now be considered implemented and will be available with the next version release. Thanks again!

**Comment by Scooty66** [comment]
Great news, thanks a lot!
[BigThumpsUp]
As I am really looking forward to that feature, about when do you plan the next version to be released?

**Comment by Sublimis** [comment]
Beta version should be released in a day or two, just to sort out something regarding pressure sensors, and the regular version probably a few days after!

**Comment by zett42** [comment]
Anyone who got VeloHero upload to work?
I get an error message like "Error uploading, please check access rights". Double checked login data.
Do I have to grant UrbanBiker upload permission on the VeloHero site? Didn't find any option like that though.

**Comment by Sublimis** [comment]
Just tested again with a brand new account, and it's working as expected. Nothing fancy, account was created, username and password were entered into Urban Biker, and upload was successful right away. Nothing special is expected to be set up on the VeloHero site prior to this. Not sure if this could be the reason, but maybe you entered your email instead of username into the "username" field?

**Comment by zett42** [comment]
I have been able to upload the most recent recording of today now, though I didn't change anything.
Upload is still failing for older tracks. 
Then I just recorded a few seconds in my home and again, the upload of this track, which is now the most recent one, fails.

**Comment by Sublimis** [comment]
Oh, ok. It seems that this problem is related to the "Power data upload policy" option on the Accounts screen. When the option is set to "Always (default)" the uploads will work, and when set to the "Upload only when...", the uploads won't work (data not accepted by VeloHero). Sorry, this is a bug in the app, and has nothing to do with login credentials etc. It won't be very difficult to solve, so the fix will certainly be included with the next version release. Thanks for pointing this out, and sorry for the inconvenience!

**Comment by zett42** [comment]
Yeah, that explains it. The two actual riding tracks, which could not be uploaded, didn't have power data. The track I recorded at home also didn't have power data. Older tracks with power data succeeded to upload.
 
Switching the "Power data upload policy" option to "Always (default)" is a good workaround for now.

**Comment by Scooty66** [comment]
Sorry for no feedback for a long time.
Works like a charm [BigThumpsUp]
Thanks a lot for adding it to the features of UrbanBiker!

Andreas
