### ISSUE TITLE
Delay altimeter

### ISSUE THREAD

**Issue by ilmi2** [Sublimis/UrbanBiker#103]
Hi,i'm trying UrbanBiker and it seems to be a very good app. With barometric sensor the altimeter works very accurate. A little problem is the delay of showing the correct high and ascent. Is there a setup option to speed up this function? 
Thanks for help

Regards Mikel

**Comment by Sublimis** [comment]
Hi Mikel, to make the altitudes accurate we need to let them through a digital filter. Every digital filter in turn causes mathematically inevitable delays. The parameters of the altitude digital filter in our app are hard-coded balanced values, that amount to about 30 to 60 seconds of delay. Currently there's no way for a user to change that.

In theory the delay could be substantially reduced when barometer is used. However, most phones react with sudden pressure changes when being handled, especially the water resistant ones. The app cannot know the difference between a real altitude change and a pressure being applied on the phone, so a stronger digital filter is in place to take care of that. We could implement an option to reduce the altitude delay, for users who have phones with a barometer that are not water-resistant. Not sure there are many of those out there, though. Which phone are you using?

Thanks for the feedback!

**Comment by ilmi2** [comment]
Hi

Thanks for your quick answer.
i'm using a Xiaomi MI8. Very good Display, but not so waterproof. I case off rain i put into my
bag.
I tryed the Jepster app. The delay is better for my use, bat the shown altitute is not realy accurate.
So i prefer using UrbanBiker.

Regards Mikel

###############################################################################
