### ISSUE TITLE
Vanishing tracks

### ISSUE THREAD

**Issue by czesio666** [Sublimis/UrbanBiker#108]
After one week of using the app I have observed that some tracks are missing. After recording is finished everything is ok. But next day it is not listed in history and no file is inside documents directory. But next day the track is visible. Nest day not visible. And I don't know if it is a problem withh app or with the system (android 8), maybe permisions.
I was looking for files in app directory but I have found nothing. Where else tracks could be stored?

**Comment by Sublimis** [comment]
Hmm, never encountered such issue before. Finished tracks are always saved to ```/Documents/UrbanBiker/track/``` folder, and nowhere else. This folder is strictly read-only to the app, except in two cases: 1) You choose to resume a track, in which case the track is transferred back to private folders and removed from the History, and 2) You choose to edit or delete a track. In other words, once a track is in the History, the app won't touch it on its own (except to read its contents). So the problem must be elsewhere.

Which method do you use to check contents of the Documents folder? Do you connect your phone to a computer for this? Maybe it could be related to this Android issue: https://android.stackexchange.com/questions/165818/some-folders-and-files-not-showing-up-on-pc-when-connected-via-usb.

The suggestion would be to restart your phone when this happens. Also, install all the latest Android updates for your phone, even if this means upgrading your Android version (e.g. your phone might be capable to upgrade to Android 9).

Let us know how this goes. Thanks for the feedback!

**Comment by czesio666** [comment]
I forgot to reply. Maybe it will be helpful for someone.
it depends on android version and/or specific brand user interface.

There are to main problems.
1. Sometimes some directories are doubled. The same name but only first letter is upper and lowercase (e.g. documents and Documents). Then, the application reads from directory where there is no saved tracks. Solution is to delete this doubled directory where there is no saved tracks.
2. Some UI have strange permission access to files in internal memory. 3rd party file managers may not show files created/modified since last device restart. One has to use UI file manager. It does not depend on device root.

My issues were observed on rooted Asus Zenfone 3 Max with Android 8 Oreo.
