### ISSUE TITLE
Recording Stationary Training

### ISSUE THREAD

**Issue by zett42** [Sublimis/UrbanBiker#114]
I'm not able to record any data while on the trainer. When I press the "record" button, the app shows powermeter data (power and cadence), but after stopping, the save/finish button does not appear. 
Also, the duration time stays at 0:00:00. 

I've set option "Do not use Location", still no recording.

Sensor properties:
[x] Use for power
[  ] Use for speed
[x] Use for cadence
[x] Use for distance and duration
[  ] Physical activity recognition
[  ] Data filtering

Any other options that might be required to enable recording of stationary training (if even possible)?

**Comment by Sublimis** [comment]
Hi, you can try enabling "Use for speed" and setting the wheel circumference option, but the chances are that this also won't work. After examining the code, it seems that in app versions v5.121 and older a power meter which is mounted on pedals or crank (the one that provides power and cadence, but not speed) cannot be used to measure duration or distance. With both duration and distance at zero, the app basically has nothing to save, thus the Finish button won't be shown.

With that being said, we've recently fixed this issue as a byproduct of considerable improvements we've made over the last month in a way the app manages sensors and does measurements. We plan to release the beta version during the next few days so you can give it a try.

Thanks for the feedback!

**Comment by zett42** [comment]
Works like a charm in latest beta. 👍
