### ISSUE TITLE
Time not stop when I am stopped

### ISSUE THREAD

**Issue by nmmanolo** [Sublimis/UrbanBiker#117]
With last versión  of the app the time doesn't stop when I am, for example, in a traffic lights with my bike. So the average is not real! Are there any solution? Thanks

**Comment by Sublimis** [comment]
Hi, are you using a heart rate sensor? When you stop, the heart rate sensor will basically continue to count duraton by default, regardless of your motion state. Using heart rate sensor for duration is a new feature in the last app version, so this is probably the reason.

This behavior can be prevented by disabling the option "Use for duration" in heart rate sensor properties screen. Hope this helps. Thanks for the feedback!

**Comment by nmmanolo** [comment]
Yes, I'm using heart rate sensor! I'll try it and I'll write you back! Thanks

**Comment by nmmanolo** [comment]
That was the solution! Thank you very much!

**Comment by Sublimis** [comment]
Thank you!
