### ISSUE TITLE
Meters are disappearing

### ISSUE THREAD

**Issue by JHenneberg** [Sublimis/UrbanBiker#119]
v5.201
Android 10

It started approximately two weeks ago, that all meters except the start button and the one right next to it disappeared. I did not payed to much attention to this because I thought I might have changed some settings accidentally. But checking the settings I could not find any evidence. All `Show or hide this meter` options are turned on and for the first two you can not even deactivate them. This happened just yesterday. I am now stuck with only the map :).
<img src="https://user-images.githubusercontent.com/6606609/109120870-cc10c800-7746-11eb-829a-96bf2367961a.jpg" width=300px><img src="https://user-images.githubusercontent.com/6606609/109120908-d92db700-7746-11eb-8015-bd3e95d60933.jpg" width=300px>

**Comment by Sublimis** [comment]
Hi, this is easy to fix 🙂  A simple tap on the "Map" button (the one on the right side, with a globe icon) will toggle meter visibility. Tap it a few more times to choose a style that fits you the most. If you want to hide the map and only show the meters, long-tap the Map button. Long-tap will always toggle map visibility, while short-tap will toggle meter visibility while map is shown.

Hope this helps. Thanks for the feedback!

**Comment by JHenneberg** [comment]
Thanks for the Help . I knew only about the long press 🤦 and the rain helped to toggle. Is this the only way to toggle through the visbility modes? If so maybe an additional button in the right side menu would be beneficial or in the "Settings"-menu I just posted in my initial comment.
