### ISSUE TITLE
Issue: specific power figures are calculated incorrectly 

### ISSUE THREAD

**Issue by PicoPET** [Sublimis/UrbanBiker#123]
Specific power is not calculated correctly:
* currently the nominal power figures are divided by **the total weight of rider + bike**
* they should be divided by **the weight of the biker alone** since the power-per-weight is a biological attribute of the biker, not of the complete rig.

Illustrative example from Sunday eve: FTP 255 W, biker below 100 kg, specific FTP 2.33 W/kg...

**Comment by Sublimis** [comment]
Hi! Yes, the app was always using a total weight so far. Now we've come up with a simple way of choosing the weight of a "Power source" from the track details screen. There are three options: Total, Driver, and Vehicle. Every option has its usefulness, like in these examples:

- Total weight is useful for electric bikes, where both the Driver and the Vehicle are power sources,
- Driver weight is useful for regular bicycles where Driver is the only power source,
- Vehicle weight is useful for motorized vehicles like cars, where Driver is not contributing to a driving force,
- Driver + Vehicle is similar to Total, but will exclude possible cargo and passengers weight from the calculation.

Please see below how this looks like in the upcoming app version, hopefully you'll like it. Thanks for the feedback!

![image](https://user-images.githubusercontent.com/3844660/114869615-7af08c80-9df7-11eb-8f62-df48af873526.png)

![image](https://user-images.githubusercontent.com/3844660/114869653-86dc4e80-9df7-11eb-894c-8b839a3184b5.png)

**Comment by PicoPET** [comment]
Good point about the different scenarios (I looked from a die-hard "mechanical" biker perspective...).

The solution looks great to me.  Looking forward to testing the update!
