### ISSUE TITLE
Why doesn't BMR in settings match BMR in ride history?

### ISSUE THREAD

**Issue by ghost** [Sublimis/UrbanBiker#124]
Love the app, but still working on getting the energy parameters tweaked.  In settings, I have entered my BMR as 54.1 kcal/hr by doing this:
Settings --> Display --> Meters --> Power and Energy --> Energy Parameters --> BMR

But in my saved tracks (under Power/Energy parameters) it lists Basal metabolic rate of 62.9 kcal/h.

What is going on?

**Comment by Sublimis** [comment]
Hi, the figure displayed in saved tracks is in fact in Watts, not kcal/h, although the units say "kcal/h". We forgot to do the conversion when showing the figure, it was noticed some month ago and already fixed for the upcoming app version.

So in your example, a BMR of 54.1 kcal/h equals 62.9 W (watt being equal to joules per second).

Note, this is only a display issue, it does not affect calculations in any way. Calculations are done properly.

Thanks for the feedback!
