### ISSUE TITLE
Issue:  Power and calories no longer working, coming out zero

### ISSUE THREAD

**Issue by LisaB66** [Sublimis/UrbanBiker#126]
Hi,

I have been tweaking the power parameters to get closer to the results I want lately and I am overall very pleased with the app.

On Friday, 4/30, the app calculated watts and calories very close to the results I think I should be getting.  The on 5/3 I changed the CdA parameter by increasing it very slightly, and got zero watts and zero calories.  I have since tested a variety of power parameter values and different riding speeds and keep getting zero watts and zero calories every time.

I am using Urban Biker with a stationary indoor bike.  I have GPS turned off and the only sensor I am using is a speed sensor.  The app continues to calculate speed, distance, and duration as expected.  It is only watts and calories that are coming out zero.

On the About screen, it says that I am using the 04/27/2021 update.  I don't know exactly when my phone installed the automatic update to this version -- perhaps I was still running the previous version on 4/30 which was the last time that power and calories worked for me.

Thanks!
Lisa

**Comment by LisaB66** [comment]
Here is the track from the 4/30 ride where power and calories worked correctly:
[2021-04-30_19-06.track.zip](https://github.com/Sublimis/UrbanBiker/files/6422235/2021-04-30_19-06.track.zip)

Here the track from 5/3 where power and calories came out zero:
[2021-05-03_19-11.track.zip](https://github.com/Sublimis/UrbanBiker/files/6422239/2021-05-03_19-11.track.zip)

I *think* the only change I made was to increase the value of CdA.  I don't remember making any other changes.  

You may notice that the parameter values that I am using are way off from what would be used in a typical road bike application.  For instance, I set driver weight to 51.6 lb and drag area of 310 ft^2.  I also have my wheel circumference at only 781mm.  This is because I am using UB for a very unusual stationary deskcycle application, where I am trying to back into a power curve that matches what the manufacturer has published.  It was working very well and I was getting very close to the results I wanted until 5/3.  Please just ignore that my parameter values are not appropriate to road bike applications, and help me to troubleshoot why the power stopped working.

Thanks!

Thanks!

**Comment by Sublimis** [comment]
Hi, the value of the parameters shouldn't play much of a role, as the app is designed to accept almost any valid parameter value. As it turns out, the real cause of the issue was too slow "clicking" of the speed sensor (i.e. very low speed). This should be resolved now in the newest version (v6.01).

However, please note that there still exists some minimal speed beyond which this once again won't be reliable. One click every 3-4 seconds should be fine, anything slower and you'll probably again be at a zero power.

Thanks for the feedback!

**Comment by LisaB66** [comment]
Sorry for the slow response, but this definitely fixed the issue.  I've been using the app almost daily and the problem has been completely fixed since v6.01.  Thanks for the prompt response.  I put in a 5-star review on Google Play for you and mentioned "very responsive developer".

As I mentioned before, I am using the app with an indoor stationary deskcycle setup, where I pedal at very low speed and resistance for long periods every day while I work at my desk.  It is analogous to walking 1 or 1.5 mph at a treadmill desk for several hours per day while working -- very slow speed and calorie burn but health benefits accrue over many hours.  The slowest I ever cycle is about 25 clicks per min on the speed sensor, so if the app requires one every 3-4 seconds is not a problem for me.  One of the main reasons I switched to UB from another well-known Android bike computer app is that it would auto-pause too often when I was going slow.  Thank you for making your app more flexible.   I also really like that when I do take a real break, the auto pause works well and then the sensors turn back on AUTOMATICALLY when I start riding again.  Perfect for me as I can take a break and then return to riding several times per day without touching the app.
