### ISSUE TITLE
Start travelled kilometer 

### ISSUE THREAD

**Issue by leon-ITA** [Sublimis/UrbanBiker#127]
if it is possible to enter the initial odometry, I would like to stop using my cycle computer but I would not want to lose the information about the kilometers traveled.

**Comment by radiotbo** [comment]
You can go to "Settings" - "Profiles" - 3 verticals dots - "Edit" - "More" and then write the correct value.

**Comment by leon-ITA** [comment]
Thnaks
But If Ido in this way change also the average speed.


In data 21 maggio 2021 20:34:08 radiotbo ***@***.***> ha scritto:

**Comment by Sublimis** [comment]
Hi @leon-ITA , just as @radiotbo said, it's the way to go. You should also change the duration if you want to keep the average speed. There's a simple relation for average speed as distance divided by duration:

`AVERAGE SPEED [km/h] = DISTANCE [km] / DURATION [h]`

So to keep the average speed, calculate the duration like this:

`DURATION = DISTANCE / AVERAGE SPEED`

**Comment by leon-ITA** [comment]
Ok thanks fo the support
