### ISSUE TITLE
Elapsed time error

### ISSUE THREAD

**Issue by leon-ITA** [Sublimis/UrbanBiker#129]
The 'elapsed time' hourglass icon showed in the chronology of run show the time between two consecutive run it should show the pause in the same run

![Screenshot_2021-05-06-08-42-07-67](https://user-images.githubusercontent.com/83750893/117338241-9ef73900-ae9e-11eb-8a0e-7fc340a6fd9e.jpg)

**Comment by Sublimis** [comment]
Hi @leon-ITA, can you please explain a bit more? We don't see a problem here, the numbers seem correct. It shows that your run lasted for 15' 46'', and you had 13h 08' 22'' of pause in between. If you wanted to record two separate runs instead, you should click the "Finish" button when asked (the prompt shows if resuming an unfinished track after more than 4 hours), or do it manually before a new run. Hope this helps. Thanks for the feedback!

**Comment by leon-ITA** [comment]
First of all thanks for the support but I believe that the elapsed time should be different from stopped time.
In this case I've finish the previous acquisition and start the new one 

![Screenshot_2021-05-23-10-18-01-23](https://user-images.githubusercontent.com/83750893/119253159-34d5d800-bbb0-11eb-83f7-72a0500a59d0.jpg)

**Comment by Sublimis** [comment]
But it is different -- **13h 24 min 08 sec** versus **13h 08 min 22 sec**. The difference being exactly **15 min 46 sec** as shown above.
