### ISSUE TITLE
Cadence/speed sensor drop out with the sensor from soospo, after a period of inactivity.

### ISSUE THREAD

**Issue by cartman-2000** [Sublimis/UrbanBiker#13]
It would seem that, after a period of time of inactivity, this sensor would enter a type of sleep mode, but the app won't gather data(doesn't reinitiate the connection to the device.) from the sensor after this happens, unless you toggle the record button in the app.

The sensor device:
https://www.amazon.com/gp/product/B07BSTJWD2/ref=oh_aui_detailpage_o07_s00?ie=UTF8&psc=1
https://www.dropbox.com/s/7sa0c91708jm4zo/Screenshot_2018-08-26-21-02-54.png?dl=0

The device being used is a samsung galaxy s5 with android 4.4(rooted).

**Comment by Sublimis** [comment]
The app will try to reconnect a sensor only when the tracking is active, and in the screenshot the tracking is not active (based on the fact that there's no 'bike' icon in the status bar area). Additionally, the time interval between two reconnect attempts can be 30 seconds when sensor is disconnected for a longer periods of time (to save phone battery).

Are you sure the tracking was active and you waited for long enough (30 seconds) for the sensor to reconnect? If this waiting period is unacceptable and you want sensor to reconnect faster, you can always fast toggle tracking by double-clicking the GPS/tracking button in the app (top-leftmost button), which will trigger immediate sensor reconnect attempt.

Please let us know whether this worked, or is this still considered a bug.

**Comment by Sublimis** [comment]
Hi, can you please try with the latest version (currently v4.22) and confirm that the bug has been fixed?
