### ISSUE TITLE
heart rate icon stay red

### ISSUE THREAD

**Issue by pelopis** [Sublimis/UrbanBiker#130]
Hi In the upper side of the screen there are icons indicating connections (gps, heart rate...) These getting green when connection is ok
I have a problem lately with the icon of heart rate which most of the time stay red although heart rate working fine and i can see it in the screen. Some times get green after some minutes and some (most of them) it never get green.
Heart rate  monitor xiaomi mi band 5
thank you

**Comment by Sublimis** [comment]
Hi @pelopis, that icon is not just for heart rate, but shows a combined status of all sensors used. It will be red if at least one sensor is not connected. So, if you use two sensors (e.g. heart rate sensor and speed sensor), and you get heart rate value while the icon is still red, it means that the speed sensor is not connected. If you do not use another sensor besides the heart rate, please go to the Sensors screen and either disable or remove unused sensors. Hope this helps. Thanks for the feedback!

**Comment by pelopis** [comment]
> Hi @pelopis, that icon is not just for heart rate, but shows a combined status of all sensors used. It will be red if at least one sensor is not connected. So, if you use two sensors (e.g. heart rate sensor and speed sensor), and you get heart rate value while the icon is still red, it means that the speed sensor is not connected. If you do not use another sensor besides the heart rate, please go to the Sensors screen and either disable or remove unused sensors. Hope this helps. Thanks for the feedback!

Thank you it solved my problem. I had an unused sensor...
