### ISSUE TITLE
Feature Request:  Song artist and title as a meter

### ISSUE THREAD

**Issue by surge919** [Sublimis/UrbanBiker#134]
There's a similar request "Basic audio player control as one of meters #69" which would be nice but hopefully this is a simpler request.

I'd like to be able to see the currently playing artist and song as a meter choice.

thanks

**Comment by surge919** [comment]
bumping this request.

@Sublimis 
What are your thoughts on this?

It would be great to be able to select a field showing the artist and song

**Comment by surge919** [comment]
@Sublimis 

new year.. old request :-)

any chance you can add this in?  on long rides, the only time i switch away from the app is to check song info if I hear something new

**Comment by JHenneberg** [comment]
Haha 😂. I guess it's quite complicated and you need more permissions to access files. I think there was a change in some android version that every app is loving in its own folder and can't break out of it. An other question is how many will benefit from this? Wouldn't it be better to address something like Spotify because it is widely more used? But also this could lead to a further request like whataburger t YouTube music and other platforms and soon you are down the rabbit hole although you just wanted to create a tracking app 😎.

Just my thoughts.

**Comment by surge919** [comment]
I wasn't sure if there was an Android call, intent, (whatever it's called) to display the currently playing artist and song title... similar to how GPS data, speed, etc is pulled

for example, if I run the following

adb shell dumpsys media_session

it returns info about the media session and shows the currently playing artist and song title

for example

      metadata: size=8, description=Every Day Is Exactly The Same, Nine Inch Nails, With Teeth

from the below command

adb shell dumpsys media_session

MEDIA SESSION SERVICE (dumpsys media_session)

5 sessions listeners.
Global priority session is com.android.server.telecom/HeadsetMediaButton (userId=0)
  HeadsetMediaButton com.android.server.telecom/HeadsetMediaButton (userId=0)
    ownerPid=1876, ownerUid=1000, userId=0
    package=com.android.server.telecom
    launchIntent=null
    mediaButtonReceiver=null
    active=false
    flags=65537
    rating type=0
    controllers: 0
    state=null
    audioAttrs=AudioAttributes: usage=USAGE_VOICE_COMMUNICATION content=CONTENT_TYPE_SPEECH flags=0x800 tags= bundle=null
    volumeType=1, controlType=2, max=0, current=0
    metadata: null
    queueTitle=null, size=0
User Records:
Record for full_user=0
  Volume key long-press listener: null
  Volume key long-press listener package:
  Media key listener: null
  Media key listener package:
  OnMediaKeyEventDispatchedListener: added 0 listener(s)
  OnMediaKeyEventSessionChangedListener: added 1 listener(s)
    from com.google.android.bluetooth.services
  Last MediaButtonReceiver: MBR {pi=PendingIntent{8c24fe8: PendingIntentRecord{484e601 com.google.android.apps.youtube.music broadcastIntent}}, type=1}
  Media button session is com.google.android.apps.youtube.music/YouTube playerlib (userId=0)
  Sessions Stack - have 3 sessions:
    YouTube playerlib com.google.android.apps.youtube.music/YouTube playerlib (userId=0)
      ownerPid=30307, ownerUid=10184, userId=0
      package=com.google.android.apps.youtube.music
      launchIntent=PendingIntent{706ca6: PendingIntentRecord{f5d06e7 com.google.android.apps.youtube.music startActivity}}
      mediaButtonReceiver=MBR {pi=PendingIntent{8c24fe8: PendingIntentRecord{484e601 com.google.android.apps.youtube.music broadcastIntent}}, type=1}
      active=true
      flags=3
      rating type=2
      controllers: 6
      state=PlaybackState {state=3, position=0, buffered position=0, speed=1.0, updated=1933605054, actions=2371511, custom actions=[Action:mName='Shuffle off, mIcon=2131232018, mExtras=null, Action:mName='Like, mIcon=2131232238, mExtras=null, Action:mName='Repeat off, mIcon=2131231991, mExtras=null, Action:mName='Dislike, mIcon=2131232234, mExtras=null], active item id=12, error=null}
      audioAttrs=AudioAttributes: usage=USAGE_MEDIA content=CONTENT_TYPE_UNKNOWN flags=0x800 tags= bundle=null
      volumeType=1, controlType=2, max=0, current=0
      **metadata: size=8, description=Every Day Is Exactly The Same, Nine Inch Nails, With Teeth**
      queueTitle=Up next, size=25
    BluetoothMediaBrowserService com.android.bluetooth/BluetoothMediaBrowserService (userId=0)
      ownerPid=6827, ownerUid=1002, userId=0
      package=com.android.bluetooth
      launchIntent=null
      mediaButtonReceiver=null
      active=false
      flags=3
      rating type=0
      controllers: 0
      state=PlaybackState {state=7, position=0, buffered position=0, speed=0.0, updated=1627896208, actions=0, custom actions=[], active item id=-1, error=Bluetooth audio disconnected}
      audioAttrs=AudioAttributes: usage=USAGE_MEDIA content=CONTENT_TYPE_UNKNOWN flags=0x800 tags= bundle=null
      volumeType=1, controlType=2, max=0, current=0
      metadata: null
      queueTitle=Now Playing, size=0
    BluetoothMediaBrowserService com.android.bluetooth/BluetoothMediaBrowserService (userId=0)
      ownerPid=6827, ownerUid=1002, userId=0
      package=com.android.bluetooth
      launchIntent=null
      mediaButtonReceiver=null
      active=false
      flags=3
      rating type=0
      controllers: 0
      state=PlaybackState {state=7, position=0, buffered position=0, speed=0.0, updated=1627896580, actions=0, custom actions=[], active item id=-1, error=Bluetooth audio disconnected}
      audioAttrs=AudioAttributes: usage=USAGE_MEDIA content=CONTENT_TYPE_UNKNOWN flags=0x800 tags= bundle=null
      volumeType=1, controlType=2, max=0, current=0
      metadata: null
      queueTitle=Now Playing, size=0
Audio playback (lastly played comes first)
  uid=10184 packages=com.google.android.apps.youtube.music
Media session config:
  media_button_receiver_fgs_allowlist_duration_ms: [cur: 10000, def: 10000]
  media_session_calback_fgs_allowlist_duration_ms: [cur: 10000, def: 10000]
  media_session_callback_fgs_while_in_use_temp_allow_duration_ms: [cur: 10000, def: 10000]

**Comment by Sublimis** [comment]
Hi! :) We don't mind adding this functionality if it doesn't turn out to be too complicated, or too hacky. Like you addressed correctly, the hard part is getting the information from the system. Did some searching, and the most reliable way seems to be using `android.media.session.MediaController` ([link](https://developer.android.com/reference/android/widget/MediaController)), and some code [here](https://github.com/QuickLyric/QuickLyric/blob/master/QuickLyric/src/main/java/com/geecko/QuickLyric/utils/MediaControllerCallback.java). However, haven't tried this, yet.

Additionally, in the documentation it says: 

> The MediaController will create a default set of controls and put them in a window floating above your application.

Not sure what to do with this, or if it would be the desired user experience.

**Comment by surge919** [comment]
For my request, I'd be happy with just presenting the artist and song info.
Issue #69 which I reference in the first post is requesting player controls so that would be a nice option :-)

**Comment by surge919** [comment]
@Sublimis have you given this any more thought?

thanks

**Comment by surge919** [comment]
@Sublimis  have you given this any more thought?

thanks

**Comment by surge919** [comment]
@Sublimis  have you given this any more thought?

**Comment by Sublimis** [comment]
Unfortunately, there doesn't seem to be an easy/standard way to do this for 3rd party (non-system) apps. [Official documentation](https://developer.android.com/reference/android/Manifest.permission#MEDIA_CONTENT_CONTROL) says:

> Allows an application to know what content is playing and control its playback.
>
> Not for use by third-party applications due to privacy of media consumption

What we're left with is to try to use a bunch of intent filters, as mentioned in [this old post](https://stackoverflow.com/a/11929681). It may work for many players but maybe not all, eg. Spotify.

Which player do you use to listen to music?

**Comment by surge919** [comment]
> Which player do you use to listen to music?

YouTube Music

**Comment by Sublimis** [comment]
It is a pity. We've had success with some other music players, but haven't been able to make it work with Youtube Music. It is not possible to find out if the application broadcasts information about the song being played at all. 🤷

**Comment by Sublimis** [comment]
Good news! Success! We managed to create a basic media info+controls meter mode, please see the screenshot below. Beta version will be available in a day or two for testing.

![image](https://github.com/Sublimis/UrbanBiker/assets/3844660/aee2eab4-8222-4d5e-a9d7-46c18b4e2378)


One caveat though, "notification access" permission is required for this to work. It's not our fault, the system is designed that way.

![image](https://github.com/Sublimis/UrbanBiker/assets/3844660/aff33d4a-4443-40cc-8b88-ad098572cd05) ![image](https://github.com/Sublimis/UrbanBiker/assets/3844660/34661801-109c-4abe-a866-6af98b51ff77)

**Comment by surge919** [comment]
Cool.. can't wait to try this

**Comment by surge919** [comment]
I installed the latest beta with the music controls as a meter.

Works great!
