### ISSUE TITLE
Is there a forum to discuss items?

### ISSUE THREAD

**Issue by surge919** [Sublimis/UrbanBiker#137]
A forum would be easier for people to ask and answer questions with input from others.
Something on a google groups or a reddit subforum would be quick and easy to set up.
I found what looks like an early attempt on google groups but it doesn't have any activity.   https://groups.google.com/g/urbanrider-app

**Comment by Sublimis** [comment]
Hi, sorry for the late reply. We've created a reddit community as you suggested, here: https://www.reddit.com/r/UrbanBiker/. Hopefully it will be helpful to everyone. The Google groups link you shared is not related to our app, but some differently named unknown app 🙂  Thanks for the feedback!
