### ISSUE TITLE
GPS is turned off after some time [Android 10]

### ISSUE THREAD

**Issue by czesio666** [Sublimis/UrbanBiker#138]
I know that there were similar posts but none of solutions works for me.

Realme RMX2111 with Android 10. Without root. GPS set in high accuracy mode. The screen is automatically turned off when the app is in foreground (i don't want ) After some time (20min, 30min, i don't know if automatic pause change it) gps is turned off. Then I turn on the screen and I can see red gps icon. Next, in a few seconds gps signal is fixed. It looks like the system is turning gps off.

I have such setting in system. 
![Screenshot_2021-07-27-13-36-06-26](https://user-images.githubusercontent.com/73993043/127148574-2756b566-43ac-4c2d-9361-91d9ebf9c7cf.jpg)
Power saver mode is off
Intensive power saver mode is off
![Screenshot_2021-07-27-13-36-24-33](https://user-images.githubusercontent.com/73993043/127148716-88f45706-f828-43b7-aa8c-bdc6a9b8d52b.jpg)
Urban biker settings:
Foreground activity is always on
Allow background activity is on

I havn't found any other options concerning battery optimization that may turn off gps.
I have tried subsystem gps and play services and also different sleep policy (fully awake). With no result. GPS sleep is off.
I have tried also some other apps to lock gps fixed. With no luck. This app also looses gps signal.

Are there any other solutions?
I have no such problem with Android 8 on rooted device. I don't know if rooting device changes anything.

At this moment I have to turn on screen each ~15 minutes to keep gps signal fixed.

Thanks in advice

**Comment by rzvolya** [comment]
on my device Redmi Note 8t, when using your application while recording a workout, if you turn off the screen in the settings, the gipies satellites are lost and the track is not recorded, when the screen remains on, this problem is not, but the battery is consumed a lot.
