### ISSUE TITLE
possibility to enter custom value in odometer

### ISSUE THREAD

**Issue by anton-vakulenko** [Sublimis/UrbanBiker#139]
Dear Developers, many thanks for great application! 
May I suggest one simple feature: make it possible to manually enter custom value in odometer. This feature is very usefull if you switched from other bike computer to UrbanBiker.
Thanks again!

**Comment by zett42** [comment]
This is already possible:
Settings > Profiles > click "edit"

**Comment by anton-vakulenko** [comment]
Many thanks for the information!
