### ISSUE TITLE
track is not recorded

### ISSUE THREAD

**Issue by rzvolya** [Sublimis/UrbanBiker#141]
on my device Redmi Note 8t, when using your application while recording a workout, if you turn off the screen in the settings, the gipies satellites are lost and the track is not recorded, when the screen remains on, this problem is not, but the battery is consumed a lot.

**Comment by Sublimis** [comment]
Hi, sorry for the late reply. This is most likely fixed with the latest app improvements, so we'll mark it as done. If you think this is incorrect, please let us know. Thanks for your feedback!
