### ISSUE TITLE
Tracks not getting recorded since v6.06

### ISSUE THREAD

**Issue by LJB2086** [Sublimis/UrbanBiker#142]
The app was working fine for me until today, and now I can't get the app to record anything.

I am using the app with an indoor stationary bike.  The only sensor I am using is a speed sensor.  I have GPS turned off.  Like I said, it was working until today.  I can't send you a log, because nothing will record now.  The speed sensor icon displays green like it always did, but now the app isn't tracking speed or distance or anything -- not even duration.

I changed a number of options yesterday such as colors and I changed the name of the profile I use.  The app continued to work yesterday after my changes, but not today, so I suspect that the new version is the problem.  

Hope you can help, because I really like the UB app!

Lisa

**Comment by Sublimis** [comment]
Lisa, we can't reproduce this issue. It looks like there could be something wrong with your speed sensor. Can you please double-check it's working correctly? We can provide you with the previous version of the app if needed, so you can convince yourself it wouldn't work with it, too (or disprove our theory!).

Thanks for the feedback!
