### ISSUE TITLE
como resolver nao mostra a velociodade e altimetria 

### ISSUE THREAD

**Issue by Wellimgton** [Sublimis/UrbanBiker#146]
no resumo maeca tudo certo mas no display fica parado

**Comment by Sublimis** [comment]
Hi, can you please try with the newest beta version? You can get it from https://play.google.com/apps/testing/com.sublimis.urbanbiker. If you can, please let us know how it went. We think this should be fixed now, but we are unable to replicate the exact issue to be certain. Sorry for the inconvenience, and thanks for the feedback!
