### ISSUE TITLE
Problem after last update 

### ISSUE THREAD

**Issue by gir0034** [Sublimis/UrbanBiker#148]
I inform that after last update I cannot view slope and speed. These data also are not recorded.
![Screenshot_20211015-163634_Urban Biker](https://user-images.githubusercontent.com/92605117/137546465-bb063237-a89a-4b23-8da1-0b1856cfe208.jpg)

**Comment by Sublimis** [comment]
Hi, can you please try with the newest beta version? You can get it from https://play.google.com/apps/testing/com.sublimis.urbanbiker. If you can, please let us know how it went. We think this should be fixed now, but we are unable to replicate the exact issue to be certain. Sorry for the inconvenience, and thanks for the feedback!

**Comment by gir0034** [comment]
Hi, I have installed v6.11 and tried but I have save problem. It doesn't record actual speed, slope,...
![Screenshot_20211016-174036_Urban Biker](https://user-images.githubusercontent.com/92605117/137595085-c4b3b78d-7bf7-435e-a392-4de9fb9580e8.jpg)

**Comment by gir0034** [comment]
My phone is Samsung A50

**Comment by Sublimis** [comment]
Can you please try now with the even more recent beta version (dated 2021-10-17)?

**Comment by gir0034** [comment]
![Screenshot_20211018-164149_Urban Biker](https://user-images.githubusercontent.com/92605117/137768452-a6f85e5e-8d9f-4c1d-84e0-59104595c5ac.jpg)
