### ISSUE TITLE
Cannot view offline map

### ISSUE THREAD

**Issue by gir0034** [Sublimis/UrbanBiker#149]
Hi, I update to v. 6.20 25-11-2021 but now I can't view offline map in my Samsung A50 with Android 11. I have set default value in offline map folder but I cannot move map file in this folder because I think it's hidden. In previous path the map isn't read. It works only online maps.

**Comment by iRomanyshyn** [comment]
The same problem with POCO X3 NFC Android 11. Can't move my data to that folder but can view it's contents. Maybe it's better to use Android/media folder to store the data because that folder seems accessible. Or maybe there is a way to make the import and export functionality to import the data from Documents folder?

**Comment by gir0034** [comment]
Hi, I connected the phone to my PC and I was able to move the map to the new path. With the file management utility on my phone I could not see any folders in the path /storage/emulated/0/Android/data/com.sublimis.urbanbiker/files/Documents/UrbanBiker/maps/. In my opinion you should find an easier way to download the map and place it in the new path. Thanks

**Comment by Sublimis** [comment]
> Hi, I connected the phone to my PC and I was able to move the map to the new path. With the file management utility on my phone I could not see any folders in the path /storage/emulated/0/Android/data/com.sublimis.urbanbiker/files/Documents/UrbanBiker/maps/. In my opinion you should find an easier way to download the map and place it in the new path. Thanks

Hi, ability to do this with a PC is a great find. However, we also succeeded by using the file management utility on a phone, the one called simply "**Files**" (see the icon attached). Other file explorers are not guaranteed to work, as they require special permissions to do this.


![image](https://user-images.githubusercontent.com/3844660/143618480-9dc1bf86-9d22-49d0-bcbb-05accf40a45f.png)

**Comment by Sublimis** [comment]
Now, the general issue with the new Android 11+ file management paradigm is that there's no public folder to be found anywhere, not even for a read-only access. By that we mean the folder freely accessible by any app, where the user can simply dump some of their "unimportant" yet highly-used files by any means they find practical. Something like the Downloads or the Documents folder before. From privacy standpoint this is understandable, but usability suffers.

When we decided some 5 years ago to use the Documents folder for our files, we didn't think the Android would close those files for the world several years later.

The fine-print, which is hard to find documented, is that Android 11+ still does allow access to files in Documents folder the old way, **but only to files the app itself created**. Offline map files and route files are never created by Urban Biker; the user creates those files using some other app. Thus, they can't be read by Urban Biker on Android 11+ the old way.

The same holds for the Android/media folder, too, and in fact any other folder you can think of, which brings us back to the fact that there's no "public" folder anywhere.

We see only two ways possible to get past this:

1. By moving files to the app-specific folders (the way we recommended in release notes).

2. By using the [SAF](https://developer.android.com/training/data-storage/shared/documents-files) to get access to files or even a whole folder (but not the Downloads folder). We may be forced to go this way in the end, but it will require significant amount of additional work, and the user experience will also not be perfect.

Thanks for the feedback!
