### ISSUE TITLE
Bluetooth sensors not connecting since Nov 24th

### ISSUE THREAD

**Issue by surge919** [Sublimis/UrbanBiker#151]
I'm not sure if it is due to one of the latest versions or something else, but none of my sensors are detected by UrbanBiker.   Polar HR monitor / Garmin Speed / Garmin Cadence

Polar and other apps are detecting the HR monitor without issue.

I uninstalled and re-installed the app.  Accepted permissions for the folders and to use Bluetooth, but none of the HR sensors are detected.

**Comment by Sublimis** [comment]
Hi, you are probably using Android 12? It requires that apps request brand new Bluetooth permissions in order to use sensors, i.e. permissions introduced for Android 12. This is not implemented in the 2021-11-25 beta version due to an oversight caused by weaknesses in official documentation. Thus, in Android 12 the 2021-11-25 beta version cannot use Bluetooth at all. Sorry about that!

Solution is to temporarily revert to the previous version v6.12, or wait for the new beta release which should be out in a few hours.

Thanks for the feedback!

**Comment by surge919** [comment]
Yes, I'm on Android 12.

I installed the latest Beta from last night and still have issues.
I tried to start fresh so I backed up all my files and wiped the following locations
/sdcard/Android/data/com.sublimis.urbanbiker/
/sdcard/Documents/UrbanBiker/

Uninstalled the app and reinstalled the Beta

When I start it up, it still sees my profile.
Is there another folder I'm missing?

Also, I'm still being asked for permissions when I view my History (which shows 2 routes even though I wiped the folders)
When I go to Settings / Sensors / Scan
I'm asked to 

![Screenshot_20211129-081032](https://user-images.githubusercontent.com/5296383/143874554-2ab72af8-a4e8-42fa-875e-dbd0c0ee72a7.png)

![Screenshot_20211129-081039](https://user-images.githubusercontent.com/5296383/143874576-b5c1b78f-6e88-417b-9762-e80012c7cb47.png)

![Screenshot_20211129-081105](https://user-images.githubusercontent.com/5296383/143874634-f90fef58-f9ec-49a9-92dd-5cbd82648602.png)


![Screenshot_20211129-081113](https://user-images.githubusercontent.com/5296383/143874655-1609eb12-5996-478f-b13a-14ce44712b25.png)

![Screenshot_20211129-081728](https://user-images.githubusercontent.com/5296383/143874988-739bae5f-d636-4c32-8be3-3654f665b7c8.png)

![Screenshot_20211129-081928](https://user-images.githubusercontent.com/5296383/143876216-4377007b-7098-4184-b57f-cc7cc557875c.png)

![Screenshot_20211129-081934](https://user-images.githubusercontent.com/5296383/143876235-793be2cd-57ca-4042-89cb-0dcb9d944458.png)

**Comment by surge919** [comment]
I noticed this has a label "Done"

The last beta didn't fix it.  Did you add the label before I added my last comment?

**Comment by Sublimis** [comment]
Hi, yes, "Done" refers to the inclusion of new Bluetooth permissions. Now we've also included "fine location" permission check when asking for Bluetooth, so it doesn't have to be granted manually.

Storage permission won't be repeatedly asked when going to History, starting with 2021-12-01 beta.

About the original query that the app sees your profiles even after you wipe the app folders. This must have been Android's "automatic backup/restore of app data" feature. The feature automatically (and transparently to user) restores app internal data folders after a reinstall. To completely wipe the app data, the recommended procedure is to also open the App info screen in Android after the app is installed, and click the "Clear storage" button. This will remove any data that may have been restored after reinstalling the app.

Hope this helps. Thanks for the feedback!

**Comment by surge919** [comment]
I've uninstalled and reinstalled and can confirm 2021-12-01 beta is working.
thanks

**Comment by Sublimis** [comment]
Thank you!
