### ISSUE TITLE
Tracks in cache

### ISSUE THREAD

**Issue by czesio666** [Sublimis/UrbanBiker#153]
Hi
How the track cache exactly works and is possible to force creating zip from these tracks in cache? Sometimes I have to wait about 10 days. Here is the content in my tracks directory. On the right one can see the date of creating of each zip files. 

edit: Ok, I found that missing zip files are in \Android\data\com.sublimis.urbanbiker\files\Documents\UrbanBiker\tracks and after some time they are transfered to Documents\UrbanBiker\tracks. Is it possible to force it?

And one other question. Sometimes I need to edit gpx due to some lost of signal. After replacing in zip file, other files like gpx.preview and svg are not correct. Is it possible to add an option to refresh these files?

![Untitled](https://user-images.githubusercontent.com/73993043/147698778-4517e66b-543e-4975-8388-15545c608cd5.jpg)

**Comment by Sublimis** [comment]
Hi, what you have described here is not the way the app behaves. Yes, starting from the v7 it will create zips inside `/Android/data/com.sublimis.urbanbiker/files/Documents/UrbanBiker/tracks` folder, but it won't transfer those files back to the old folder `/Documents/UrbanBiker/tracks`. Also, it never uses the `//tracks/` folder like shown in your screenshot.

Are you sure you haven't set up some automatic backup task (using some other app) that you forgot about?

As for refreshing files, only the preview files could be easily refreshed after editing the gpx. SVG files contain much more data than the gpx, and that data comes from a variety of sources (not just the lat/lon coordinates of the gps) so unfortunately it wouldn't work this way.

Thanks for the feedback!

**Comment by czesio666** [comment]
Yes, maybe I was working on older version and did not noticed version change. Thus I thought track files should be transferred to Documents\UrbanBiker\tracks.
After some time I noticed that all zip files are in \Android\data\com.sublimis.urbanbiker\files\Documents\UrbanBiker\tracks

Thanks
