### ISSUE TITLE
Elapsed time doesnt Start at zero

### ISSUE THREAD

**Issue by ub-use** [Sublimis/UrbanBiker#154]
Hello, since some Weeks elapsed time does Not start at 00:00. It Looks Like it jumps to the time since GPS Signal is reachable from the device, e.g. after leaving building. 
Pixel 4a
Android 12 january 2022

**Comment by ub-use** [comment]
![Screenshot_20220116-111625~2](https://user-images.githubusercontent.com/69647885/149655929-d83957d5-ed2b-4cfb-aeb4-e04357e0401b.png)
Bevore starting

**Comment by ub-use** [comment]
![Screenshot_20220116-111636~2](https://user-images.githubusercontent.com/69647885/149655960-09212924-49a6-41ac-977a-72995f13b0a9.png)
After starting

**Comment by Sublimis** [comment]
Hi, we've addressed this issue and published a beta app version yesterday with a possible fix. Problem is that we can't reproduce the issue and be certain that it has been fixed. If possible, you can try the beta version [here](https://play.google.com/apps/testing/com.sublimis.urbanbiker) to see if the issue is still present or not.

Thanks for the valuable feedback!

**Comment by ub-use** [comment]
I've installed Version 7.04 from 2022-01-24.First Trip today started with 0:00After a Short Break next Trip startet with 8:xx.Next Trip started with 2:xxLast Trip in the evening after longer Break of some hours started with 0:00Issue seems not to be fixed.Best regardsLutzAm 25.01.2022 23:09 schrieb Sublimis ***@***.***>:
Hi, we've addressed this issue and published a beta app version yesterday with a possible fix. Problem is that we can't reproduce the issue and be certain that it has been fixed. If possible, you can try the beta version here to see if the issue is still present or not.
Thanks for the valuable feedback!

**Comment by Sublimis** [comment]
Hi, please try with the latest beta version dated 2021-02-01. The theory is that the system sometimes sends an outdated location update upon tracking start (esp. after a longer break), so we've now implemented a shielding for that.

Thanks for the feedback!

**Comment by ub-use** [comment]
Hello, the issue seems to be fixed. Am 02.02.2022 14:15 schrieb Sublimis ***@***.***>:
Hi, please try with the latest beta version dated 2021-02-01. The theory is that the system sometimes sends an outdated location update upon tracking start (esp. after a longer break), so we've now implemented a shielding for that.
Thanks for the feedback!
