### ISSUE TITLE
Add SystemDateTime in the main screen

### ISSUE THREAD

**Issue by Vlumak** [Sublimis/UrbanBiker#155]
This would avoid to have to minimize the app to be able to see the current time in the phone while biking.

Configuration: Show: date/time/both. DateFormat: DD/MM/YYYY / DD/MM/YY / Others. TimeFormat: hh24:mm / hh24:mm:ss

It would go at the bottom, in a new line (just on top of the menu-button line). This new line in the screen could be separated from the rest with a double line or another way, to be noticed as it is something of the system and not relationed with the biking activity.

You could move the Start/Pause/Stop button to this line. The button could be smaller. It is only pressed when you are stopped, not biking.

You could also add in this line a new param Temperature, gotten from Internet if connected.

**Comment by Sublimis** [comment]
Please see #157 .
