### ISSUE TITLE
Configure the parameters visualization in the main screen

### ISSUE THREAD

**Issue by Vlumak** [Sublimis/UrbanBiker#157]
Choose the parameters (distance, duration, energy, ...) to show and the position in the screen.

This could be great, because everybody could have it as liked, but, if not possible, have, at least, a "compact view", including only distance, duration and speed, and the new system-date-time and temperature suggested in my previous issues. 

When you look at the screen, you have to turn your head down. If you have less parameters, your look is faster. It seems something stupid, but if your look lasts more seconds, you could have an accident. The faster you go to the information you want, the more secure the action is.

For me, the rest of the information (altitude, energy, power...) is very useful, but to check it after you have ended your biking.

**Comment by Sublimis** [comment]
Hi, when you long-click any meter field on the screen a menu will pop-up, where you can choose which metric to show in that field. There is a metric called "Clock" which will show the current system time. Date is not shown, but we could consider implementing this, too. There's also a "Temperature" metric, but it will show either a value from a sensor if available, or a computed value from the phone's CPU temperature; not from the Internet. This is also something we can consider implementing.

You can reduce the number of fields on the screen by going to **Settings > Display > Meters > Meter modes**, and disabling some of the meters. We are currently trying to implement better customization of the main screen, with the main goal to allow the customization to be done from the main screen, i.e. without going to the Settings screen. It's a complex thing to do, so it may be done in steps (over several app versions), but it should be complete in the next month or so.

Funny thing is, users usually ask for more meter fields on the screen, not less; You seem to be the first to understand why we thus far never implemented more than 5 fields on the main screen. 👍 🙂 

Thanks for the feedback!

**Comment by Vlumak** [comment]
Oh! I hadn't realized that it's possible to reduce the number of fields on the screen and change its position, or that there was a clock around there. Now I have the screen as I wanted, and it looks really cool. Thank you!!!
