### ISSUE TITLE
Bike paths on map

### ISSUE THREAD

**Issue by Tired12** [Sublimis/UrbanBiker#16]
The Google Maps app has a layer for bike paths in addition to satellite or traffic.  Any chance you could add this layer to the map in Urban Biker?

**Comment by Tired12** [comment]
So I found that the bike paths are on the map after all, you just have to zoom in sufficiently and look carefully enough to see them.  So I'll modify the request: can they be made more visible (the narrow light green lines are hard to see) and can they show up when more zoomed out.  Thanks

**Comment by Sublimis** [comment]
In latest version update, v4.25, we introduced **OpenCycleMap** map from Thunderforest provider. This map shows bike paths even on large zooms, so this may be what you're looking for. Please note however that we are forced to charge for Thunderforest maps, as they are not free and require monthly payment.
