### ISSUE TITLE
Different word in spanish

### ISSUE THREAD

**Issue by Vlumak** [Sublimis/UrbanBiker#160]
When you go to the Historial, you have the parameter "Eficiencia" in the spanish language ("Efficiency" in english, I guess). When you click on it to see the description, the pop-up window is entitled "Eficacia (acumulado)" instead "Eficiencia".

**Comment by Sublimis** [comment]
Hi, you can influence this translation here: https://translate.urban-bike-computer.com/translate/urban-biker/strings/es/?checksum=14a2a9e0d762d1f4. Thanks for the feedback!

**Comment by Vlumak** [comment]
I have tried to change it, but the "Save" button is always disabled. The bad translation is on "Efficacy", that appears as "Eficiencia" and should be "Eficacia". The same word starting in lower-case is right: "efficacy" is translated as "eficacia", and also "Efficacy (cumulative)", translated as "Eficacia (acumulado)". I have pushed the "Suggest" button. I don't know if that's enough.

**Comment by davorpa** [comment]
@Sublimis I've applied your suggestion :wink:

@Vlumak, as the main translator in spanish/galeician/asturian let me know if there are more issues to get an accordance.

Moreover, you need signup/signing to directly save instead of suggest, better if link with GitHub to count your contributions
