### ISSUE TITLE
Connect with Velo Hero grayed out in Accounts

### ISSUE THREAD

**Issue by ryahp** [Sublimis/UrbanBiker#169]
I tapped "Connect with Velo Hero" in Accounts but nothing happened and the button is now grayed out.

I might have double tapped or otherwise mistapped the button. Re-starting the app or the phone did not help.

Is there a way to reset the button so that I can connect to my Velo Hero account?

**Comment by Sublimis** [comment]
Hi, are you using Android 5? VeloHero connection will only work on Android 6 and newer.

Hope this helps. Thanks for the feedback!

**Comment by ryahp** [comment]
Ah yes, I'm using an old phone running Android 5.
The button could have been more informative if it had told me why it was disabled.

Thanks.
