### ISSUE TITLE
Android 12 problem

### ISSUE THREAD

**Issue by karpeshinn** [Sublimis/UrbanBiker#173]
[2022-05-30_07-37.track.zip](https://github.com/Sublimis/UrbanBiker/files/8802664/2022-05-30_07-37.track.zip)
[2022-05-31_07-44.track.zip](https://github.com/Sublimis/UrbanBiker/files/8802665/2022-05-31_07-44.track.zip)
Nokia XR 20, after update to android 12, I take problem , when i switch app's on the screen track is paused.
Android 11 work normal.

**Comment by Sublimis** [comment]
Hi, sorry for the late reply. Based on the track dana, we think this has nothing to do with changing apps, but instead that you've set up your **speed sensor** wrong.

In the first track (05-30, Android 11), there's no speed sensor used, and everything seems normal.

In the second track  (05-31, Android 12), speed sensor is used for distance (and duration), but it doesn't work normally. It measures distance to be only about 40% of the real value. We suggest you to fix or adjust the speed sensor: replace battery, align the magnets, check the "Wheel circumference" value in sensor properties, replace the sensor with another one, or if you cannot fix it then simply disable it.

Hope this helps. Thanks for the feedback!
