### ISSUE TITLE
Cannot connect to Strava

### ISSUE THREAD

**Issue by srthimsen** [Sublimis/UrbanBiker#182]
On the authorization page when attempting to connect to Strava, I click "Authorize", but it immediately kicks me back to the settings screen and doesn't connect.

Google fit works without issue. 

V7.5 (2022-11-17)
OnePlus 8T
Android 13 (AOSP build, not rooted)

**Comment by AlixcarsGps** [comment]
alguna ayuda con respecto a la conexion con strava ya que no se conecta....

**Comment by Sublimis** [comment]
Hi, this was fixed just yesterday (for the upcoming v7.62), after we finally found the problem and managed to replicate it. Sorry it took so long and thanks for the feedback!
