### ISSUE TITLE
Cannot transfer tracks to new phone - Android 13 permissions problem

### ISSUE THREAD

**Issue by howardcochran** [Sublimis/UrbanBiker#183]
Hello, I follow instructions given in the FAQ to migrate all my tracks to a new phone.  I was able to copy all the files under /Android/data/com.sublimis.urbanbiker/files/Documents/UrbanBiker/ from my old phone (Android 10 / Galaxy Note 9) to my computer using ssh + rsync.

However, there appears to be no way to either read nor write to this folder on my new phone (Android 13 / Google Pixel 7).  Nor any other foder wihin /Android/data/.  This includes using apps such as cxFileExplorer or ES File Explorer which use the Storage Access Framework. From this document, it appears that Google broke this functionality on purpose starting in Android 11: https://developer.android.com/training/data-storage/shared/documents-files

Since the Phone-to-phone cable transfer did not move this data during phone setup, users appear to be really stuck unless UrbanBiker developers do something about it.

My suggestions:
1. In the settings, allow the user to designate a different directory for storing this data anywhere they want under external storage (typically /storage/emulated/0).
2. When the user changes this setting, ask them whether to move all existing data to the new location.

This gives flexibility back to the user to decide whether they want their data inside this ridiculous walled garden, vs. in a location that Android will allow them to acces.  It is MY data; Google is WRONG to prevent me from accessing it!  But you (UrbanBiker authors) have the power to liberate it from the black hole that is /Android/data.

**Comment by Sublimis** [comment]
As it turns out, this is the same problem as #197, and the solution, once we come up with it, will also be the same.
Sorry for the waiting.

**Comment by Sublimis** [comment]
Have you ever figured out why the UrbanBiker data wasn't moved by the Phone-to-phone cable transfer during phone setup? Was this specific to UrbanBiker, or the data from other apps wasn't moved as well?
Thanks for the feedback!
