### ISSUE TITLE
Add "stop time" and "moving time" (enhancement)

### ISSUE THREAD

**Issue by motobird** [Sublimis/UrbanBiker#19]
I think it'll be beneficial to have total "stop time" (total time that bike/car is not moving for whatever reason) and "moving time" (total time that bike/car is in motion).

**Comment by Sublimis** [comment]
Stopped time done, will become available in the next version!

Moving time is essentially the same as Duration, especially if auto-pausing is used (and by default it is used). Thanks for the feedback!

**Comment by motobird** [comment]
Thank you! Looking forward to it!
