### ISSUE TITLE
SRM-XP Power meter pedals

### ISSUE THREAD

**Issue by onley** [Sublimis/UrbanBiker#190]
I have the SRM-XP Dual power pedals and urban biker will only recognize one pedal so indicated power is only for one leg. Is there a way to get it to recognize both pedals and show total power for both legs?

**Comment by Sublimis** [comment]
Hi! If I understand correctly, with these pedals you see two separate Bluetooth power sensors when you search for sensors inside Urban Biker, one for the left and one for the right pedal?

As a workaround, would enabling the Zwift mode help? Or using the ANT+ connection (if your phone has this feature)?

Thanks for the feedback!

**Comment by onley** [comment]
I will try the zwift mode as a work around but I paid an extra $400 for the dual pedals and zwift mode takes away my ability to get power balance and I have had a balance problem due to ACL replacement so balance is the primary reason for the pedals.

**Comment by onley** [comment]
Zwift mode works as a work around but messes up the pedal app and power balance indication.

**Comment by Sublimis** [comment]
Hi, the v7.76 beta version which supports this feature will be out shortly (in about an hour). You can register here, if you haven't already: [https://play.google.com/apps/testing/com.sublimis.urbanbiker](https://play.google.com/apps/testing/com.sublimis.urbanbiker). Let us know how it works!
