### ISSUE TITLE
Export heart rate to Strava

### ISSUE THREAD

**Issue by Ruden2007** [Sublimis/UrbanBiker#191]
I recently bought a heart rate monitor.  UrbanBiker quietly records the pulse during a workout, you can see the graph with it, but when exporting to Strava, the pulse is not displayed in Strava

**Comment by Sublimis** [comment]
Hi, we cannot replicate this issue, everything works fine. Please check the permission on Strava. When you open the Settings on the Strava website, there is a section titled "**Data Permissions / Health-Related Data**", where you must give your consent to Strava so it can use the data like heart rate.

Explanation from the website is as follows: "Strava collects and uses health data from paired devices, like a heart rate monitor, to give you interesting and useful performance analysis. We collect this data only from sensors or devices you've connected to Strava. We do not share it without your consent."

Hope this helps, thanks for the feedback!
