### ISSUE TITLE
Phone battery indicator

### ISSUE THREAD

**Issue by pickednamenoway** [Sublimis/UrbanBiker#194]
Can't read the phone battery level while cycling (its dangerous since the little size display on android system).
There is really no way to show the battery level, like for example do you have it for the time?

**Comment by Sublimis** [comment]
Hi, this has not been implemented yet. It seems like a popular request, so we might as well prioritize it. In the meantime, may I suggest another solution: an app like [PowerLine](https://play.google.com/store/apps/details?id=com.urbandroid.inline). Would this help?

Thanks for the feedback!

**Comment by tdurack** [comment]
I use the "Energy Bar" app to have a colored gradient line along the top of the screen indicating battery level. I find that works well for UB and in general. A battery meter in UB might be useful though!
