### ISSUE TITLE
Transfer data and settings to new mobile phone

### ISSUE THREAD

**Issue by Scooty66** [Sublimis/UrbanBiker#197]
Hello,

really great bike-app which I already use for years.

Having a new mobile phone (Pixel8), unfortunately none of the ways described in the FAQ for transfering data and settings to the new phone work for me.
With none of the tools I have at hand (as recommended in the FAQ like Autosync or Cx File Explorer) can I get the permissions on the new phone to create/write/access the directory /Android/data/com.sublimis.urbanbiker/files/Documents/UrbanBiker etc.

Maybe I am just not smart enough to find a possible solution, but is there another way to transfer the data/settings to a new phone or even better, are you intending to include this kind of function (export/import or even cloud-sync) in the app itself?

Really would like to hold all data in the app on the new phone, not to mention avoiding the manual effort of recreating profiles/displays :-).

Thanks for your support,
Andreas

**Comment by Sublimis** [comment]
Hi!

Have you tried using the ["Files by Google"](https://play.google.com/store/apps/details?id=com.google.android.apps.nbu.files) app that came with the phone? It's possible that the only reliable way to get permissions to access files/folders in `/Android/data/` is to use this app, since it's a system app.

As for the export/import feature, yes, it is planned for the future.

Please let us know. Thanks for the feedback!

**Comment by Scooty66** [comment]
Hi and thanks for the swift reply.
Yes, indeed, I tried the Google Files app. Actually when starting with the Cx File Explorer for copying, as soon as I enter the target directory it asks to switch over to the Google Files app to try to gain access, but all options for gaining access are greyed out.
But also using Googe files app right all the way for copying only gives as as result a message like "Could not copy".
So I am now kind of deperately looking for you implementing some kind of export/import feature. :-)
Any idea yet about a possible timeframe for implementing?
As an intermediate solution I will be using my old phone for cycling, but any swift availability of this feature would of course be highly welcomed. :-) 

Andreas

**Comment by Sublimis** [comment]
Please note, the folder `/Android/data/com.sublimis.urbanbiker/files/Documents/` does not exist unless the application is installed, so you should manually create it. Does this help?

You can also try using the "standard Android transfer apps and data to the new phone" way ([please take a look here for Pixel 8](https://support.google.com/pixelphone/answer/7129955)). However, this will only work if your previous phone also saved UrbanBiker data to `/Android/data/...` and not just `/Documents/...` . If this is the case, maybe you can "trick" the system by first copying your `/Documents/UrbanBiker/` folder to `/Android/data/com.sublimis.urbanbiker/files/Documents/UrbanBiker/` on your old phone? Whatever you do, please make a backup of your data first.

As for the timeframe, this is going to be a lot of work, so the export/sync feature availability certainly can't happen swiftly, sorry :)

**Comment by Scooty66** [comment]
Hi,
thanks for your tips.

Unfortunately manual creation of folder also is not possible due to lack of access rights in /android/data directory.

For the Android transfer apps you refer to I think they only work for fresh/out-of the box/resetted Pixel8s.
So all the work having done on setting up the phone already for quite a number of other apps would be lost. :-(
Or do you hav any idea (ok, ok, this question goes way beyond the scope of support for UrbanBiker :-) ) to restart the  "standard Android transfer apps and data to the new phone" way?

Sorry to hear about the effort needed to develop an export/sync feature. For future-proof usage of the app not only for new devices from my point of view this definitely would be a great feature.

Andreas

**Comment by Scooty66** [comment]
As a workaround to at least be able to see all the old tracks on the new phone I am using now:

- created a directory `/Documents/UrbanBiker/tracks`
- copied all files from a backup of my old phone from `/Android/data/com.sublimis.urbanbiker/files/Documents/UrbanBiker/tracks/` to `/Documents/UrbanBiker/tracks`
- chose "History" from the main menu, upper rigt menu chose "Custom tracks folder" and point to `/Documents/UrbanBiker/tracks`
- all old tracks are now visible in "History" (which actually is absolutely fine for me).

OK, that unfortunately does not help with any profiles (and totals)/settings/layouts I defined on the old phone.
Maybe a feature to only export/import these thimgs is easier/quicker to implement?
But for the time being I am happy now with the workaround.

Andreas

**Comment by Sublimis** [comment]
What is confusing, is why the application data (ie. profiles and other config) wasn't automatically restored after you installed the app? This should obviously have happened even if you didn't transfer the app during the initial device setup wizard, as [officially desribed here](https://developer.android.com/guide/topics/data/autobackup#RestoreSchedule).

I guess the only requirement for this to happen is that you use the same Google account on both phones. If you haven't, maybe you can add the previous account as a second account on the new phone, and install the app from there?

**Comment by Scooty66** [comment]
Thanks for your continuous support.
Looks like I had messed up things beforehand somehow as I am also not able to give you an explanation for the standard functions not working properly.
As also I seem to be the only one having had these problems I do not think it's worth following up further. And I am fine with the current solution.
Maybe just adjusting/adding info to the sections in the FAQ for the current standard way would already be fine.

**Comment by Sublimis** [comment]
As it turns out, this is the same problem as #183, so it looks like you're not the only one. We'll reopen this issue for now.
