### ISSUE TITLE
Since version 8.03 no height/ascent/descents are recorded

### ISSUE THREAD

**Issue by Scooty66** [Sublimis/UrbanBiker#202]
Hi,
noticed that since version 8.03 no height (max-min)/ascent/descent are recorded (at least with me).
Or I am missing a new setting I need to enable?
Happy to provide any further information required.
Running Urban Biker on Pixel 8. Android 14.

Thanks for your support,
Andreas

**Comment by tdurack** [comment]
Same here - Motorola G7 Power running Lineageos 21 (Android 14)

**Comment by Sublimis** [comment]
Hi guys, the issue has been resolved and a new release v8.04 has been created. It is now up to Google to review and publish the release. Hopefully it won't take them too long.

Until then, a quick fix is to disable the Online elevation option in Settings > Tracking/GPS > Altitudes. (Note that this is a per-profile option)

Sorry about this, and thanks for the feedback!

**Comment by Sublimis** [comment]
Update: The fixed release v8.04 is now available to all users on the Play Store, and as a standalone APK [here](https://github.com/Sublimis/UrbanBiker/tree/master/APK).
