### ISSUE TITLE
App Ver. 8.20 from 2024-07-25 sometimes becomes unresponsive

### ISSUE THREAD

**Issue by fbsoftware-stuttgart** [Sublimis/UrbanBiker#206]
Hi, 

since Ver. 8.20 from 2024-07-25, (and i think the version from 2024-07-06 was also affected) sometimes the app becomes slow and unresponsive and the current gauges (like speed etc.) won't update anymore.  This can become so bad that the whole device becomes unresponsive and you only can switch it off.

And then the device can only switched on again after it has been cooled down.

The only thing i notice is that the second icon from the left at the top of the app screen has become red when this happens.

So maybe this happens, when the contact to the GPS sattelites is lost for a short time?

To me it looks like there is an infinite loop happening somewhere causing this problem.

My device: Samsung SM-A530F/DS Galaxy A8 Duos (2018) with Android 9

Thanks and regards.

**Comment by Sublimis** [comment]
Hi! Please try disabling the "Adaptive" GPS update interval feature, which is enabled by default. This feature may not work well with your device. You can do this in Quick Settings or on the Settings > Tracking/GPS > General screen.

Additionally, you can try changing the "GPS provider" feature in the Settings > Tracking/GPS > Advanced screen.

If that doesn't help, please send us a debug report ("Report an issue" from the main menu) including the debug.log file(s).

Please let us know how it went, and thanks for the feedback!

**Comment by fbsoftware-stuttgart** [comment]
Hi,

the "Adaptive" GPS update interval feature was already disabled.

"GPS provider" feature was "Google Play". I've changed it to "GPS Subsystem" now.

I'll have to watch and see how the app behaves. This may take a few days up to a week or so. I'll give you a feedback then.

I also looked into the debug1.log file and found nothing suspicious.

But another thing i just found: by changing the GPS update interval on the Settings > Tracking/GPS > General screen you can crash the app by clicking one time more when the setting is already at the limit. Works both with upper and lower limit...

**Comment by Sublimis** [comment]
No problem. Quick question, do you use offline maps? This may sound strange and perhaps unrelated, but we noticed (and fixed) some minor (for us) unresponsiveness when using offline maps. It could be something, it could be nothing, it's hard to say because we can't replicate your issue.

As for the GPS update interval dialog, this was caused by a simple oversight on our part that became apparent after we switched to the new Material style sliders. It has nothing to do with the main issue, unfortunately.

One more thing. We recently found that clearing the data of the "Google Play Services" system app can help solve various problems with it. It may not be obvious to the user, but our app uses Google Play services, for example to get locations (when the GPS provider option is set appropriately), as well as to recognize user activities (walking, cycling, etc.). We had problems with the latter, without changing anything in our code, and the only thing that solved it was deleting the service data. However, be aware of all the consequences if you choose to do so.

Many thanks!

**Comment by fbsoftware-stuttgart** [comment]
So, i could only do a short test with v8.21 (about 10 min/4 km) and it worked flawlessly.

As opposed to v8.20, which crashed my phone today again after approximately 3 min.,,

**Comment by fbsoftware-stuttgart** [comment]
Ok, after one week of testing, it seems v8.21 fixes the issue.

So, congrats.

I'm gonna close the issue.

**Comment by fbsoftware-stuttgart** [comment]
Sorry guys, i have to reopen the issue: with v8.21 from 2024-8-2 i had no issues, with v8.21 from 2024-8-7 my phone became unresponsive after ca. 3 minutes today again, so that i could do nothing else but hard shutdown the phone (keep the buttons on the side pushed, till the phone powers off).

I noticed, the gauges weren't updating, pushed the phones back button "<" and then the phone freezed completely.

After restarting the phone and the app, the profile i was using, was gone. Instead it showed "Restored profile" but all the data was reset to zero. Also the layout changed back to default.

What i noticed with v8.21 (and i think already with v8.20) is a change in lock screen behaviour, meaning, the app doesn't prevent the lock screen anymore.

So after a few seconds you stll see the app, but the "|||" button disapears (the button that shows you all open apps) and with the other buttons, you only get to the lock screen and you have to unlock the phone first before you can continue.

What i want to say: maybe there is a deadlock happening somewhere which causes the phone to become unresponsive.

**Comment by Sublimis** [comment]
Does this happen only after (or during) interacting with offline maps?
Do you use hill shading ("Render terrain" option)?
Is you phone overheating maybe?

It would be most helpful if you could find what triggers such behavior, i.e. some repeatable steps after which you could say "now it will happen".

Offline maps were the biggest change for the v8.20 and v8.21, and depending on the theme selected they can now use significantly more CPU to render than before (especially on lower spec devices). There were no changes to our threading model or other low level code. You were right that an infinite loop may be causing this; deadlocks usually do not cause high CPU usage, instead threads just sleep and do nothing waiting for each other. On the other hand, any OS should be more than capable of terminating a misbehaving app even if it goes into an infinite loop, so phone freezing and restarting is indication of some OS or firmware problem really - or overheating. (This shouldn't happen, but of course we'll do our best to try to find and fix the issue with our app)

Thanks for the feedback!

**Comment by fbsoftware-stuttgart** [comment]
Strange thing is: most of the times this happened, the app didn't have to render any maps at all.

Most of the time i ride routes i know, so i don't need any maps, but use only the gauges.

Unfortunately there are no repeatable steps, which trigger that behavior. It seems to happen randomly during the ride.

The last interaction i've had with the app was always just starting the recording of the track - nothing more. Then after a some time you realize the gauges won't update anymore and then you interact with the phone again (first by trying to stop and restarting recording, and since the app isn't responding, by typing the back button in order to close and restart the whole app) - and then you realize your phone freezed...

Only one time when this happened, the app had to render maps - but that was already 2 hours or so into the tour. That's what i reported in my first post of this issue (red icon and the phone wouldn't power on again until hours later i put it in the freezer for a few minutes). 
But later on the same day, i used the app (v8.20 from 2024-07-25) with map rendering to navigate me another 60 km (2,5 to 3 hours) and it worked flawlessly.


When this happened yesterday with v8.21 from 2024-8-7, no maps to render, only the gauges view.  I cycled a short round trip between 7.30 and 8.30 pm. 1.6 km on the way there, stopped half an hour, 1.9 km on the way back.

On the way there, no problems. On the way back: I started recording and started cycling - after ca. 3 min the gauges weren't updating but all the three icons from the left at the top of the app screen were green. I tried to stop recording but the app wasn't reacting. Then I pushed the back button and the phone freezed completely.
When i was home after another 2 minutes or so the phone didn't feel particularly hot - it powered on immediately after i powered it off.

The behavior of the phone at the point before i powered it off feeled like a deadlock.


Today i switched back to v8.11 (apk file from the github repo). I cycled the same round trip as yesterday at about the same time of the day.

On the way there, the phone suddenly restarted during the ride.

On the way back, it seemed i had the same situation as yesterday on the way back, ie the gauges wouldn't update anymore, but: the app stayed responsive. The GPS icon (second from the left) turned red. I could stop the recording and restarting it, the app found the gps sattelites again and continued recording.

When i was home, i wanted to finish recording, ie save the recorded track into a file and this wouldn't work: i saw the circle going round indicating processing, but it wouldn't finish and the phone didn't react to typing the "home" or "back" button.

So after a minute or so, i had to power the phone off and on again.


Too long, didn't read:
My guess at the moment is, how the app recovers when the gps signal is lost for some time...
Assuming, my phone is not broke and assuming it is the app causing the phone to freeze, that is where i would start to look...

**Comment by Sublimis** [comment]
How much free storage space is there on the phone? Please ensure a minimum of 1 GB at all times, even if the app doesn't need it, the system might.

Do you have all the latest system updates installed? If not, please update everything, Android OS, Play Store, Play services, everything you can.

And most importantly, please enable "Usage and diagnostics" option in the Google section of your Android's settings. ("Help improve your Android device experience by automatically sending diagnostic, device and app usage data to Google. [...]")
When an ANR (app not responding) event occurs, there *should* be a dialog like the one below, and when you click to close the app, a diagnostic data is collected (and sent to Google, and then to us, when you connect the phone to the internet via wi-fi).
Without this data it's really hard to debug without the device in our hands, for example the problem could be with the code in one of the libraries that the application uses...

![anr](https://github.com/user-attachments/assets/f7e8ce6d-ebce-4cf2-afd7-a95a62a4959c)

**Comment by Sublimis** [comment]
Please also try disabling the "GPS auto sleep" and "Reduce GPS noise" options (Settings>Tracking>Activity recognition).
Additionally, also try disabling the "Pocket mode" (Settings>Display>General), "Waving mode", and "Screen stabilization" options...

**Comment by Sublimis** [comment]
So the freezes and restarts only happen when the app is used while the device is **locked**? Does it ever happen otherwise?

**Comment by fbsoftware-stuttgart** [comment]
Yes, it does. Ok, so the lock screen can't be the only reason, i don't see any ANR dialogs.

Settings on my device are, by shortly hitting the on/off button on the side twice, i can lock the device.

I did a few tests today with v.8.22 to see, if i can force the issue by locking the device during recording - no luck.

v8.22 stays "issueless" up to the moment...

**Comment by fbsoftware-stuttgart** [comment]
So, my phone is officially broke - seems to be a hardware problem all along.

Issue closed.
