### ISSUE TITLE
Magene Gemini 210 Speed/Cadence Sensor not working via Bluetooth

### ISSUE THREAD

**Issue by zett42** [Sublimis/UrbanBiker#29]
This sensor supports both Bluetooth and ANT+. I'm trying to get it to work via Bluetooth because my phone (LG G7) doesn't support ANT+.

**Steps**:
- Sensor switched to speed mode.
- Scan for sensors through settings / sensors.
- Sensor is correctly detected as speed/cadence sensor.
- Added sensor. Sensor is now listed under "used" tab.
- Entered sensor settings and disabled automatic wheel circumference, set a fixed value of 2000 instead.
- Started track recording.
- Spun the wheel to let the sensor send some data. 

**What happens**:
- Speed field stays at 0 km/h. Distance field isn't updated either.
- Sensor shows as "connected", but signal level shows question mark.
- In the MyWorkouts app (http://www.myworkouts.org/) the sensors correctly measures speed, so this probaply is a software issue, not a hardware one.

**Did this work in a previous version?**
Don't know, it's the first time I'm trying to use this sensor with UrbanBiker.

**Device model and Android version**:
- LG G7 with Android 8.0.0 (security patch level: February 1st, 2019)

Sensor manufacturer page:
https://translate.google.de/translate?hl=de&tab=wT&sl=zh-CN&tl=en&u=http%3A%2F%2Fwww.magene.cn%2Fgemini.html

**Comment by Sublimis** [comment]
Hi, is it possible that you are using very old version of Urban Biker? We had similar issue report last year, and made some changes and improvements regarding this in August 2018. Could you please check the version and update to the latest if necessary (currently it's v5.06). Let us know how this went, so we can take further steps as needed. Thanks for the feedback!

**Comment by zett42** [comment]
I've just checked. About page shows v5.06 (2019-03-30). I'm using the Pro version, if that makes any difference.

**Comment by Sublimis** [comment]
No, Pro version doesn't make a difference here. Could you please try another thing. 'Connected' status for a sensor should only be possible when tracking is active (or paused) and the sensor is awake. Are you sure you had tracking active (GPS button on main app screen is red and shaped like 'Stop')? Maybe the reason is this simple, and the app wrongly displayed 'Connected' for a sensor which in fact wasn't connected. When a Bluetooth sensor is properly connected, it should always display signal level without a question mark, without exception.

One more thing if the above doesn't help, is it possible that maybe you have to wake up both speed and cadence parts of the sensor for it to connect properly? Unfortunately we can't test this sensor model ourselves as we don't own one. We'll order one if nothing else helps, but the shipping will take weeks.

Thanks again!

**Comment by zett42** [comment]
> Are you sure you had tracking active (GPS button on main app screen is red and shaped like 'Stop')? 
Yes, I just double checked again. Tracking is active and sensor shows "connected" with question mark on the signal level.

Also I just noted that the sensor status icon at the top (the 4th from the left, which is shaped like a heartbeat diagram in a circle), was red immediately after I started tracking. It turned green once I awoke the sensor by spinning the wheel.

> is it possible that maybe you have to wake up both speed and cadence parts of the sensor for it to connect properly
I don't think so. A single sensor can only measure either speed or cadence, but not both at the same time. You first set its mode and then either mount it on a crank or the hub. It detects rotation through its orientation in the geomagnetic field of the earth (according to the manufacturer).
I have double-checked that it is in speed mode. This is also confirmed by the other app (MyWorkouts) I tested it with, which correctly shows the speed.

**Comment by Sublimis** [comment]
Sensor icon going from red to green is good behavior. Sorry, we misunderstood that you have both Speed and Cadence parts of the sensor.

Now, the Bluetooth specification only recognizes combined Speed+Cadence sensor, and not separate Speed and separate Cadence, as can be seen here: https://www.bluetooth.com/specifications/gatt/services. Does this mean the sensor is always advertised as Speed+Cadence (Bluetooth service number 0x1816), just that one or the other is not working depending on sensor setting?

You can get more info on services the sensor provides by using e.g. the nRF Connect app: https://play.google.com/store/apps/details?id=no.nordicsemi.android.mcp. Maybe you could write down the services for us, or send us a screenshot. Unfortunately we have no other ideas about the issue at this time, as we can't find any problem with the code.

Thanks!

**Comment by zett42** [comment]
Here is a screenshot of nRF Connect.
![Screenshot_2019-04-03-18-39-33](https://user-images.githubusercontent.com/18427509/55497688-2e87e900-5642-11e9-9479-6189479742bb.png)

**Comment by zett42** [comment]
Service 0x1816 expanded:
![Screenshot_2019-04-03-19-04-32](https://user-images.githubusercontent.com/18427509/55498268-7a875d80-5643-11e9-8a0b-19e72022f522.png)

**Comment by zett42** [comment]
**CSC Feature** reads this flag:
Wheel Revolution Data Supported

**Comment by zett42** [comment]
I just set the sensor to cadence mode. Now the CSC service outputs this:

![Screenshot_2019-04-03-20-57-43](https://user-images.githubusercontent.com/18427509/55505581-b1fe0600-5653-11e9-9718-76068246111c.png)

Hope this helps!

**Comment by Sublimis** [comment]
Sorry, we can't find anything strange on this screenshots. All the info appears okay, and comparable to other Bluetooth CSC sensors. Seems like we'll have to acquire the sensor for debugging.

One last thing you can verify though, is that this issue is not caused by some battery saving feature on your device (set on per-app basis). You can try disabling battery optimizations for Urban Biker and then testing the sensor again. Also check that the app has all the permissions it needs (i.e. nothing is blocking its access to Bluetooth functions). Without the sensor in our hands, unfortunately this is all we've got for now...

Thanks for all the info!

**Comment by zett42** [comment]
> You can try disabling battery optimizations for Urban Biker

I've disabled power saving for Urban Biker, but still no luck. 

> check that the app has all the permissions

Checked. App has "open Bluetooth settings" and "connect to bluetooth devices" permissions.

One other thing I just noticed: After removing the sensor from the "used" tab, deleting it from scan results page and doing a rescan, the signal level icon shows full bars. Once I've added the sensor again, the signal level is no longer recognized (shows question mark). Also battery icon of the sensor shows question mark.

> All the info appears okay, and comparable to other Bluetooth CSC sensors. 

Good. This sounds to me, that you will likely be able to get the sensor to work, after fixing or working around some minor quirks (of the sensor or Urban Biker ;-)).

> Seems like we'll have to acquire the sensor for debugging.

Great. For what it's worth, the sensor is very cheap compared to Garmin and others (especially if you only need either speed or cadence) and it was delivered reasonably fast (less than 2 weeks) from China to Europe.

Thanks!

**Comment by Sublimis** [comment]
Sorry, still waiting for the delivery. We'll examine this as soon as we get the sensor!

**Comment by Sublimis** [comment]
It has arrived. We'll get down to business and let you know our findings over the next few days, when we'll also publish a fixed beta version, hopefully.

**Comment by Sublimis** [comment]
So, we examined the sensor and found out that it really *is* advertising a Cycling Power service. This is not visible in the above screenshots, but can be seen in the same nRF Connect app *before* connecting the sensor (in the Scanner tab). It says: **Complete list of 16-bit Service UUIDs: 0x1818, 0x1816**. 0x1818 stands for Cycling Power, and 0x1816 stands for Cycling Speed and Cadence.

This would all be nifty as Cycling Power service also has Speed and Cadence fields incorporated. However, the Cycling Power service is in fact not implemented. When sensor gets connected, the service is simply not available. It's not that our app is doing something wrong here; it's just not prepared to handle devices lying about their services.

We will fix this for the next version, but it will involve some more work. Simple workaround would be to use ANT+ communication for the sensor, but unfortunately as we see your phone doesn't support ANT+.

**Comment by zett42** [comment]
Great to see some progress here! 
Your analysis is very understandable.

You are right, my phone doesn't support ANT+, so a fix for BT will be very welcome.

**Comment by Sublimis** [comment]
Hi, we've just released a beta version (v5.10b) with this fixed. Please check it out! You can get it from: https://play.google.com/apps/testing/com.sublimis.urbanbiker. It was really complicated to implement this fix so a tiny bug here or there should be expected, although we did our best to leave no bugs.

Gemini 210 sensor will now be recognized as Speed/Cadence/Distance/Duration/Power sensor, but the 'Power' service will be discovered as spurious and removed from the list upon first connection.

**Comment by zett42** [comment]
Awesome, first test ride has given good results! I've send you further details by mail.
