### ISSUE TITLE
movimiento del mapa

### ISSUE THREAD

**Issue by alejanalejan** [Sublimis/UrbanBiker#3]
(spanish)
Por favor... cuando viajo en el modo mapa ya sea en bicicleta o auto, el mapa no se mueve  en tiempo real
y permanece fijo sin cambios como por ejemplo sucede con la app Waze, que si se va miento el mapa mientras uno se traslada....

me podrían indicar como se corrije o como se debe parametrizar urban-traker para lograr el efecto que el mapa se mueva?

gracias de antemano.

**Comment by Sublimis** [comment]
Hi @alejanalejan,

Please long-click on the map until a dialog pops up. There you'll see 'Follow' and 'Auto rotate' options. Please enable both for this effect.

Thanks for the feedback!

**Comment by alejanalejan** [comment]
perfecto.... ambas no las tenía activadas... lo acabo de hacer y esta noche
probaré si funciona.....

thanks a lot!

Atte., RTC.

**Comment by alejanalejan** [comment]
from Chile!

Atte., RTC.
