### ISSUE TITLE
Sensor settings reset on app update

### ISSUE THREAD

**Issue by Niflheim123** [Sublimis/UrbanBiker#32]
I have a cadence sensor that I use it only for cadence (its set in sensors - only for cadence). I have received two app updates and the other settings get enabled (use for speed, distance). The app should remeber my settings on update.

**Comment by Sublimis** [comment]
This has been fixed in the latest update. Please make sure to update the app to version v5.10 dated 2019-06-01, and everything should work okay. However if sensor properties got changed for you in the previous app version, unfortunately you'll have to set them up again, sorry about that.

**Comment by Niflheim123** [comment]
I confirm that the fix works.
