### ISSUE TITLE
display issue when using spilt screen

### ISSUE THREAD

**Issue by Scooty66** [Sublimis/UrbanBiker#34]
Hi there,

until current version (v5.13 2019-06-21) very happy to use Urban Biker.
Mainly in split screen mode together with Locus Maps.

Since latest version I experience a display issue in split screen mode. The upper part to start/stop recording is not shown correctly anymore and not usable. Only happens in split screen mode.
Please see screenshots below.
Anything I can do about it?

Happy to provide any further information/tests.

Thanks,
Andreas

PS: Running on a Mi Mix 2S with Android 9 and MIUI 10.3.3
 
![Screenshot_Urbanbiker_Fullscreen_OK](https://user-images.githubusercontent.com/5012764/59974258-58e6a400-95aa-11e9-8d1e-b972ec96db2d.png)
![Screenshot_Urbanbiker_SplitScreen_NOTOK](https://user-images.githubusercontent.com/5012764/59974259-597f3a80-95aa-11e9-8484-fd8660bceb59.png)

**Comment by Sublimis** [comment]
Hi Andreas, we've fixed this promptly and released a fixed version yesterday (v5.14, 2019-06-23). This turned out to be caused by an update to a Google library our app uses for its UI. Google updated the library (called constraint-layout), which introduced this bug without us noticing and without changing anything else. So the only thing left to do was to revert to the old library version, as we did for v5.14.

Thank you for the valuable feedback!

**Comment by Scooty66** [comment]
Thanks for the swift fix, works perfect again!

**Comment by Scooty66** [comment]
Hi Sublimis,

again there is a display problem in split screen mode on my device (Xiaomi Mi 10, Android 11 RKQ1.200826.002, MIUI Global 12.2.4) with Urban Biker v5.2000.
Meter values are somehow too wide in their boxes:
![Screenshot_2021-02-19-17-51-00-325_menion android locus pro](https://user-images.githubusercontent.com/5012764/108535788-fa704c80-72db-11eb-90fe-be304719f237.jpg)

Any idea how to resolve? 

Thanks for your support,
Andreas

**Comment by zett42** [comment]
Same problem here. LG G7, Android 10, Urban Biker 5.200.

I suggest to hide the icons if there is not enough space for both icon and digits. Most of the time I know what kind of information the fields show by looking at the unit and the formatting.

**Comment by Scooty66** [comment]
Thanks for implementing these suggested changes in v5.201.
Looks good!

Andreas

**Comment by Sublimis** [comment]
Just wanted to say @zett42 that your suggestions were implemented in the latest beta version, but @Scooty66 beat me to it. Thanks to you both! 👍

**Comment by zett42** [comment]
Awesome, much better now! Thanks for quick response!
