### ISSUE TITLE
APK download for devices w/o Play Store

### ISSUE THREAD

**Issue by scy** [Sublimis/UrbanBiker#40]
Thanks for this app! It's been so hard to find one that reliably supports external sensors and does _not_ switch to GPS speed as soon as it's available. _And_ one that provides a comprehensive export with all the important data.

I'm currently running Urban Biker on my tablet (in my bag, just for tracking), because my phone is running LineageOS and has no Play Store, which means I can't install UB. It would be awesome if you could provide an official APK download. I know that there are third-party services that provide APK downloads outside of the Play Store, but I don't trust them to not mess around with the APKs.

Simply adding releases here on GitHub, where everything is HTTPS and has signatures and stuff would be alright with me, but if you wanted, you could use your own website, too. Using GitHub would have the additional advantage of notifications about new releases though.

**Edit:** Not having a Play Store (and the Google Play Services) will of course probably result in some issues regarding ads and licensing …

**Comment by Sublimis** [comment]
Hi, we've created a folder "APK" here on GitHub, where we'll be putting all the latest APKs: https://github.com/Sublimis/UrbanBiker/tree/master/APK.

Currently you can find the latest app version there (v5.32), plus the last versions to support Android 4.2+ and 4.0+ (v5.20 and v4.26). Hope this helps.

Thanks for the feedback!
