### ISSUE TITLE
Automatic disconnection from Strava account

### ISSUE THREAD

**Issue by scigradbd** [Sublimis/UrbanBiker#51]
Even though I have already connected my Strava account with UrbanBiker (Settings > Accounts), on attempting to upload a track, I am presented with a "Connect with Strava" orange button. [Hitting this button takes me to a Strava authorisation page. After hitting "Authorize", I'm taken back to the upload dialog/pop-up box where the "Connect with Strava" button has not converted (as should be expected) to "Disconnect". I'm able to upload my tracks but after multiple attempts and only if I hit the blue "Share" button quickly enough. 

Entering Settings > Accounts again shows me a "Connect with Strava" orange button. Here too, hitting the button takes me to a Strava authorisation page. Again, after hitting "Authorize", I'm taken back to the previous page (list of accounts) where again the "Connect with Strava" button has not converted (as should be expected) to "Disconnect".

Troubleshooting:
Cleared UB cache --> no change
Cleared UB app data  --> no change
Revoked access to UB on Strava website, reentered password (verified password is correct) and regranted permission to UB on the Strava authorisation page (mentioned in issue description)  --> no change

**Comment by Sublimis** [comment]
We confirm the issue, and are now testing the solution. Fixed version should be available during the next 24 hours (beta, at least).

Reason behind the issue is that, due to recent changes in Strava API, the StravaZpot library we used to negotiate with Strava servers is not able to handle this anymore. Since it also appears abandoned, we are now migrating away from it.

Thanks for the detailed report, it helped a lot!

**Comment by scigradbd** [comment]
Hey, thanks for the reply! Just want to update you that after posting the issue, I tried to use the Share button (on the Upload dialog) without doing the "Connect to Strava" step and it worked fine. It only *looks* like I am disconnected, but I'm still connected.

Will await the update patiently (sadly, have lost my phone, so I have no other choice). Thanks for all that you do. I absolutely love UB and cannot do without it.

**Comment by JHenneberg** [comment]
I can confirm the problem. I installed the Beta early morning today but it is not working. It could not connect to Strava at all. I tried the authorization process with the strava app itself and also with the browser. After granting access and returning to the app the connection is still not established.

**Comment by Sublimis** [comment]
Hi @JHenneberg, @scigradbd, we've published a new beta version just now, and this should be completely fixed at last. Is it possible for you to try again? The thing is, login went fine but the app failed to acknowledge success. Also, it sometimes worked, sometimes not. Thanks for all the feedback!

**Comment by JHenneberg** [comment]
I just started the season and my legs feeling pretty weak after today short ride :). For testing purpose I will go for an other short test ride tomorrow I guess.

**Comment by Sublimis** [comment]
Can you please try the Strava login part only? You can do that from the couch 🙂 Glad to hear that the season has started!

**Comment by tdurack** [comment]
I have the same problem - waiting for the new beta to appear in play store, then will install and test

**Comment by JHenneberg** [comment]
I can install only v 5.51 at the moment.

**Comment by Sublimis** [comment]
The newest version will also carry the label v5.51, but is dated 2019-01-27 (as opposed to yesterday's beta version dated 2019-01-26). It is basically a release candidate, and will be propagated to a full release shortly after we get a confirmation here that the Strava login and sharing indeed works correctly.

Play Store says the update is still pending, it's been a few hours now. Hopefully this will happen soon, but until then the exact same APK can also be taken from here: https://github.com/Sublimis/UrbanBiker/tree/master/APK.

**Comment by tdurack** [comment]
Updated - strava account reconnected. Will test post-ride tomorrow. Thanks for the fix!

**Comment by Sublimis** [comment]
Thank you for the confirmation!

**Comment by JHenneberg** [comment]
Connection seems to stay established yes.

**Comment by tdurack** [comment]
Verified working in the field - thanks!

**Comment by scigradbd** [comment]
Unable to test (lost phone a week ago and will be a while before I can replace it), but thanks for the fix! I'm good to sign off since others have confirmed the fix works.

I'm currently using an older phone (KitKat) for my riding needs, and it's running a much older version of UB (from an exported APK back when UB still supported older phones). Interestingly, I do not face this problem at all on this phone.

**Comment by BayuHanggoro** [comment]
Hi,
I just tried Urban Biker, test it on the road and love it!
Problem is I could not automatically sync my exercise into my Strava account.

Android v.6.0.1 (and on other mobilephoe  Android v9 also experienced the same problem)
Urban Biker v 5.91

From UB - Setting - Account
Choose "Connect with STRAVA" - Autorization page - Choose AUTHORIZE
Immediately there was text and voice message said "Some errors occurred. Please try again"
It then showed "Disconnect" orange button.

I check from STRAVA web - My Apps menu. Urban Biker was listed there.
I removed it and try again from beginning. Same problem.

Please help how I can sync my activity directly to Strava.

By the way, by using GPX file from My document/Urban Biker folder, I can manually create new activity in Stava. Great!
