### ISSUE TITLE
when the screen is rotated, the map is not drawn

### ISSUE THREAD

**Issue by AlexandreZaytsev** [Sublimis/UrbanBiker#54]
v5.60  (2020-02-21)

Map offline
...
I click on the map icon to update the image

Device - xiaomi mi a3 (android 9)

**Comment by AlexandreZaytsev** [comment]
Map offline
...
I click on the map icon to update the image

**Comment by Sublimis** [comment]
Hi, this bug was confirmed and resolved just now, so the next release will have it fixed. Thanks!
