### ISSUE TITLE
[GPX] [Strava] Heart Rate and Cadence not exported 

### ISSUE THREAD

**Issue by JHenneberg** [Sublimis/UrbanBiker#55]
v5.60

Unfortunately the heart rate and cadence is no exported neither to strava or to *.gpx although it looks like it is recorded. When I check in the overview window of the app there are values for "Heart Beats", "max" etc.

When I export older segments to *.gpx the heart rate is still written onto the file.

**Comment by Sublimis** [comment]
We've identified the bug and resolved it just now. The bug was indeed introduced in v5.60 beta, so the previous regular version is not affected, luckily. The updated beta version will be available shortly. Thanks for this! 👍

**Comment by JHenneberg** [comment]
I guess the data is lost of those segments?

**Comment by Sublimis** [comment]
Unfortunately yes, but it can be restored with some work. If you had SVG graphs generation enabled then you only lost information which links cadence, heart rate and temperature data to geocoordinates+timestamp. SVG graphs will still contain all the data linked with distance and duration of the ride. With some coding and relatively simple algorithm, GPX file containing all the data could be restored and then uploaded to Strava if desired (upload to Strava involves simply a GPX file upload, from which Strava then extracts all the relevant info).

**Comment by JHenneberg** [comment]
Thanks for the advice. I had a look into the *.gpx and also in the *.svg of the same activity. I was expecting the same amount of data, but they dont match. I tried to find out by comparing ```<gpxpx:PowerInWatts>``` with the corresponding ```*distance-power.svg``` but they dont match by there values either. So I guess to really match them you have to calculate the distance from the at and lon and the interpolate the datapoints of ```*distance-heartrate.svg``` to match the datapoints in *.gpx. To much work for only two workouts :)
