### ISSUE TITLE
Feature Request: Battery Meter

### ISSUE THREAD

**Issue by tdurack** [Sublimis/UrbanBiker#56]
Would like to have a battery percentage meter display.
Estimated remaining runtime might also be useful.

Thanks for considering!

**Comment by Sublimis** [comment]
This is an interesting suggestion, but can you please elaborate a bit more about usage scenario. Is it important for you that this info is big and very visible on the screen (like the rest of meters)? Why is Androids' own battery icon in statusbar not enough (and its own estimated remaining time in settings)?

**Comment by tdurack** [comment]
Good question - the status bar is too small to see when out on the road, and digging through settings for estimated runtime is similarly impractical when you are miles deep :)

I am currently using an "Energy Bar" app which gives a nice battery percentage color bar across top of screen. This works well except that Energy Bar vs. Urban Bike App doesn't always result in the Energy Bar staying on top (I need to figure out if I can resolve that through app settings or screen pinning)
