### ISSUE TITLE
Screen orientation not preserved after screen off/on

### ISSUE THREAD

**Issue by tdurack** [Sublimis/UrbanBiker#58]
Screen orientation is not preserved when screen is toggled off/on.

I work around it by setting screen orientation in app control panel.

This is on a Moto g7 Power, Android 9 in case it matters.

**Comment by Sublimis** [comment]
Hi Tim, we cannot replicate the issue. Are you using app version v5.60? What's your screen orientation setting in Control panel? Please note that when it's set to "Automatic", the screen will orient itself based on your default setting (most often the sensor orientation, if you've enabled automatic orientation in Android), and won't try to preserve the orientation. All other settings (Portrait, Landscape...) should always preserve the orientation while the app is visible. Using these settings when you want the orientation preserved is indeed a way to go!

**Comment by tdurack** [comment]
v5.61 beta - behavior same with previous versions.

Android settings auto-rotate disabled - that means the android rotate button appears on rotate.
Urban biker set to auto-orientation.
Rotate to landscape
Press android rotate button
Turn screen off
Turn screen on
Screen comes on in portrait, have to press rotate button again - kind of tricky when riding :)

**Comment by Sublimis** [comment]
It seems like this is the default Android behavior. It also happens on Android 10, and with all other applications. There's really not much we can do about it :) We suggest you to use the "Landscape" screen orientation option from the Control Panel when you need to. (This option is global, applies to all profiles. It was per-profile option some time ago, but we made it global to make things more intuitive, hopefully this isn't too inconvenient if you change between orientations a lot.)

**Comment by tdurack** [comment]
Got it - thanks for checking
