### ISSUE TITLE
Transparent search button is in the middle of the screen

### ISSUE THREAD

**Issue by radiotbo** [Sublimis/UrbanBiker#62]
Map search function. The transparent button is in the middle of the screen in landscape orientation instead of at the top part of the map as you say and where it will be more intuitive, in the same place where the search box appears. Thenk you for this great app!!!

**Comment by Sublimis** [comment]
Sorry, cannot reproduce this issue. Which Android version are you using? Can you provide a screenshot, by first enabling "Show layout bounds" in Android Developer settings? Thanks!

**Comment by radiotbo** [comment]
The search button is at the same level than the my location Google Button.

![Screenshot_2020-03-14-20-19-04-441_com sublimis urbanbiker](https://user-images.githubusercontent.com/61949860/76689230-154e3180-6634-11ea-9967-5e910ca94634.jpg)
![Screenshot_2020-03-14-19-55-09-170_com android settings](https://user-images.githubusercontent.com/61949860/76689231-15e6c800-6634-11ea-9e0d-439faf526f17.jpg)
