### ISSUE TITLE
style of rec button

### ISSUE THREAD

**Issue by ranXeron** [Sublimis/UrbanBiker#66]
I´d like to request: 

option to match the style of the rec button ( currently a colored  pseudo 3D object)  to the design of the main screen  (flat monochrome LCD).

**Comment by Sublimis** [comment]
Hi, is the main concern 3D appearance of the button, or the fact it's colored white/red? Any specific suggestion how to improve this would be appreciated. Our main goal was to differentiate the button from the rest of the controls, to emphasize its much higher relative importance. Thanks for the feedback!
