### ISSUE TITLE
Basic audio player control as one of meters

### ISSUE THREAD

**Issue by djcinek** [Sublimis/UrbanBiker#69]
I know this is sort of breaking the logic of interface as controls are not meters, 
but is it possible to add as new "meter" to display simple bar with buttons like previous, next, play/pause.
I listen to music a lot during trainings and switching between apps is a nightmare.

**Comment by mmveets** [comment]
I like the idea

**Comment by iRomanyshyn** [comment]
Also, it might be cool to make some volume regulator based on current speed.

**Comment by radiotbo** [comment]
Probably you need a bluetooth media control. It is cheap and works great. I used a lot.

[https://m.es.aliexpress.com/item/4000358219901.html?spm=a2g0n.detail.0.0.190f6c38vfudCE&gps-id=platformRecommendH5&scm=1007.18499.130806.0&scm_id=1007.18499.130806.0&scm-url=1007.18499.130806.0&pvid=67e75d42-d100-42b5-93f8-6ddd30ac8293&_t=gps-id%3AplatformRecommendH5%2Cscm-url%3A1007.18499.130806.0%2Cpvid%3A67e75d42-d100-42b5-93f8-6ddd30ac8293%2Ctpp_buckets%3A668%230%23131923%2367_668%23888%233325%2310_8499%230%23130806%231_8499%234696%2321885%2318_668%232846%238112%231997_668%232717%237564%23647__668%233374%2315176%23149&browser_id=1089d9def8c8426e8d130abda40e788b&aff_trace_key=ca2de7415e55414d9a94dbfd25580238-1611843648920-03537&aff_platform=msite&m_page_id=fbpffyefnhkcavgm1775a13e41ff1a4b41f2301c4a&gclid=&_imgsrc_=ae01.alicdn.com%2Fkf%2FH6e3ea35d777145618f8a3dc037c10fe3v.jpg_640x640Q90.jpg](https://m.es.aliexpress.com/item/4000358219901.html?spm=a2g0n.detail.0.0.190f6c38vfudCE&gps-id=platformRecommendH5&scm=1007.18499.130806.0&scm_id=1007.18499.130806.0&scm-url=1007.18499.130806.0&pvid=67e75d42-d100-42b5-93f8-6ddd30ac8293&_t=gps-id%3AplatformRecommendH5%2Cscm-url%3A1007.18499.130806.0%2Cpvid%3A67e75d42-d100-42b5-93f8-6ddd30ac8293%2Ctpp_buckets%3A668%230%23131923%2367_668%23888%233325%2310_8499%230%23130806%231_8499%234696%2321885%2318_668%232846%238112%231997_668%232717%237564%23647__668%233374%2315176%23149&browser_id=1089d9def8c8426e8d130abda40e788b&aff_trace_key=ca2de7415e55414d9a94dbfd25580238-1611843648920-03537&aff_platform=msite&m_page_id=fbpffyefnhkcavgm1775a13e41ff1a4b41f2301c4a&gclid=&_imgsrc_=ae01.alicdn.com%2Fkf%2FH6e3ea35d777145618f8a3dc037c10fe3v.jpg_640x640Q90.jpg)

**Comment by Sublimis** [comment]
Good news! Success! We managed to create a basic media info+controls meter mode, please see the screenshot below. Beta version will be available in a day or two for testing.

![image](https://github.com/Sublimis/UrbanBiker/assets/3844660/aee2eab4-8222-4d5e-a9d7-46c18b4e2378)


One caveat though, "notification access" permission is required for this to work. It's not our fault, the system is designed that way.

![image](https://github.com/Sublimis/UrbanBiker/assets/3844660/aff33d4a-4443-40cc-8b88-ad098572cd05) ![image](https://github.com/Sublimis/UrbanBiker/assets/3844660/34661801-109c-4abe-a866-6af98b51ff77)

**Comment by djcinek** [comment]
Woooooow, you remembered!
<3 <3 <3

djc

pt., 14 cze 2024 o 17:41 Urban Biker ***@***.***> napisał(a):

**Comment by Sublimis** [comment]
It wasn't so much remembering as it was dealing with technical difficulties and poor documentation. 😁 Thanks for everything!
