### ISSUE TITLE
Two heartrate sensors active

### ISSUE THREAD

**Issue by JHenneberg** [Sublimis/UrbanBiker#75]
Hey, 

I have an HR strap and a Xiaomi Mi band 3. I can add both devices for measuring the heartrate. I wanted to compare the two against each other to determine accuracy of the Mi band in real world conditions. I can't figure out if both are recorded or only the one I added first to the profile or the median is calculated from both. Can you shed some light on this topic?

Greetings Julian

**Comment by Sublimis** [comment]
Hi, when two sensors provide the same type of data (be it heart rate, speed, cadence, or power) only one will be used for recording purposes, but there's no easy way of telling exactly which one. The app will choose the first one from the internal list sorted by hashes, but that's almost random when looked from the outside. [Although, it can be determined by examining the _sensors.json_ file in app's config folder.] However, the app will then stick to that sensor throughout the activity. That is, unless the sensor disconnects, in which case the app will transparently shift to some other available sensor.

So the only real benefit of using two or more sensors of the same type is to provide redundancy and continue recording data even if some of the sensors fail mid-activity. At this time there's no way of recording data streams of multiple same-type sensors separately. We suggest using multiple phones for this purpose, or using some app dedicated to logging sensor data (not sure which one, if one even exists, though).

Hope this helps. Thanks for the feedback!

**Comment by JHenneberg** [comment]
Hey,
 thanks a lot for the detailed answer and keep up the good work and excellent customer support.
