### ISSUE TITLE
Screen lock results in to less illuminated screen

### ISSUE THREAD

**Issue by JHenneberg** [Sublimis/UrbanBiker#76]
Hey again,

to avoid accidental touches in rainy conditions I am using the screen lock feature but unfortunately it darkens screen. Changing the brightness manually is instantly reverted. At least for me it would be beneficial to have an option to turn of the lowering of the screen brightness.

Greetings Julian

**Comment by Sublimis** [comment]
Julian, the feature will be available in the next release. Luckily, it was an easy one 🌝 .  Thanks for the feedback!

**Comment by JHenneberg** [comment]
That sounds great 👍
