### ISSUE TITLE
Power Meter Data?

### ISSUE THREAD

**Issue by tdurack** [Sublimis/UrbanBiker#78]
I see UB now exports power data as a power meter to strava which is pretty cool.

I see the data exists for old rides too, but I have to delete and re-upload to strava. Is it possible to just re-upload and have strava add power data? (This might really be a strava feature request rather than UB, just checking...)

**Comment by Sublimis** [comment]
When uploading an activity to Strava, our app merely uploads GPX file to their servers (along with some unimportant metadata). What happens next is up to them. It seems like they do not re-process activities that already exist, defining activity existence just by looking at GPX track timestamp, not the whole contents. This is understandable, as processing a track is a lengthy operation that takes (server) time and money. However, they could easily implement some smarter way of determining activity existence, if they wanted to. Maybe you can suggest to them.

So the answer would be no. In theory this could be achieved be letting the app delete old track first before uploading again, but this would potentially lead to loss of track metadata, e.g. if the user edited track info with Strava, uploaded photos, etc. So we better not mess with that.

Thanks for the feedback!

**Comment by tdurack** [comment]
Understood - thanks for the clear response!
