### ISSUE TITLE
Add 2 meters per line in app

### ISSUE THREAD

**Issue by Niflheim123** [Sublimis/UrbanBiker#8]
Hello,
I was wondering if it`s possible to add 2 meters per line in app (for example I have a heart rate monitor that has a lot of unused space left, it would be nice to add 2 meters per line like heart  + cadence).
Thank you. (awesome paint skills to illustrate the issue)
![screenshot_20180726-121324](https://user-images.githubusercontent.com/11680904/43253563-f1a41ec6-90cd-11e8-83b6-43230c461680.png)

**Comment by motobird** [comment]
I concur and if possible, adding more meter lines will be great too. Also, if adding more meters per line (or adding more lines) increases the battery consumption, then I suggest removing the little numbers on the lower left and lower right corners as they are not readable when riding anyway.

**Comment by Dieggu** [comment]
I agree also. That was exactly, what I was searching for.

**Comment by Niflheim123** [comment]
the gained area can be used to display the sensor information on a more detailed level (connected, disconnected etc)

**Comment by radiotbo** [comment]
Please, as phones are getting biger it would be nice to have the option to add at least one more line and 2 meters per line will be perfect!!!

**Comment by surge919** [comment]
Has this been implemented?  The screenshots show 2 per line but I can't find how to do it?

<img width="673" alt="Screen Shot 2021-06-18 at 10 13 48 PM" src="https://user-images.githubusercontent.com/5296383/122628162-98a1d280-d082-11eb-8644-ea8ec5ed3d64.png">
