### ISSUE TITLE
Wrong right menù (italian)

### ISSUE THREAD

**Issue by Carlocor** [Sublimis/UrbanBiker#89]
It seems a wrong right menù in italian language. It repeats twice Power/Energy settings.
And, even if the extra load Is 0,5kg, It shows 1.0kg. See attached photo. And also something wrong on Rolling resistance.

![Screenshot_20200718-125613](https://user-images.githubusercontent.com/42035121/87851308-cffa8300-c8f7-11ea-94a3-7c5dd8e6c1b8.png)

**Comment by Sublimis** [comment]
Hi, thanks for pointing this out. It's been fixed now, and the next version won't have those errors. Thanks for the feedback!

**Comment by Carlocor** [comment]
Version v5.102 solved the problems. 👍
