### ISSUE TITLE
Strava and Heart rate data

### ISSUE THREAD

**Issue by Andrewman2** [Sublimis/UrbanBiker#90]
I have Heart rate sensor  the Polar h10. Application can read data  and showing real time heart rate. But when i export  the data to the Strava, heart data lost.

**Comment by Andrewman2** [comment]
Was need to set premission on Strava to analyze heart rate data lol.

**Comment by Sublimis** [comment]
Lol, thought something weird is going on with Strava again. Glad it worked in the end! 😃
