### ISSUE TITLE
Question: Did one of the recent updates get rid of Google Maps and Satellite Views?

### ISSUE THREAD

**Issue by crabtre** [Sublimis/UrbanBiker#92]
One of the recent updates seems to have restricted me to only Thunderforest maps.  Was this planned or is it abnormal behavior?

Appreciate the help.

Samsung S10+ 
Android v10
Kernel 4.14.117-18725736

**Comment by crabtre** [comment]
Nevermind... All are there.  My bad.

**Comment by Sublimis** [comment]
Hi, as you realized by now, the trick is to click the "Back" button to get to the root dialog which lists all map providers. We've improved this for the upcoming version, as can be seen in the image. We'll leave it here for anyone who comes across this problem in the future. Thanks for the feedback!

![image](https://user-images.githubusercontent.com/3844660/89540498-65a17800-d7fd-11ea-9eb4-b6fae829480a.png)
