### ISSUE TITLE
Feature Request: Show Left/Right Balance of Power

### ISSUE THREAD

**Issue by zett42** [Sublimis/UrbanBiker#94]
Many powermeter devices record left and right pedal power separately. 
It could be useful to show L/R balance, to be able to focus on the weaker leg in training.

The output could be a decimal number between -1 and 1, for instance. If negative, the left leg produces more power, otherwise the right leg produces more power. To get a more stable value the output should propably be an average over a significant amount of time (say 15 s). For me it is not important to see an exact value, but it should be possible to see a tendency. Of course a total average of L/R balance would be useful on the summary page.

I could give you sample data from Favero Assioma Duo powermeter.

**Comment by Sublimis** [comment]
Hi, yes this is possible and should be useful to implement in the future. We'll try to make it happen as soon as possible, but it's not expected that this feature will make it to the release version until the late September. Sample data would be greatly appreciated, and you can send it to us via contact email for example. Thanks for the feedback!

**Comment by onley** [comment]
Zett42, when you setup your pedals do they show up as separate sensors? Left and right pedals? I am trying to setup the SRM-XP dual pedals and I added both pedals to the profile but only get power data from one pedal. How did you configure your sensors, maybe I can learn something about how to connect my SRM-XPs.

**Comment by zett42** [comment]
Sorry, I'm no longer using UB for this purpose. I've since switched to using a garmin edge, which correctly differentiates between left and right pedal and logs much more data. 

I've just tried to connect the power sensors to UB and it only adds the left pedal. The right pedal is listed under "not supported". There might be nothing wrong as I believe that only one pedal actually sends the data for both pedals to the recording device. The other pedal is only connected to the 1st pedal.

**Comment by onley** [comment]
Yes, it seems most of the dual pedals use one master and one slave but the SRM X-Power seems to be two pedals that communicate individually. There is a Zwift compatibility mode but they recommend leaving it off unless connected to Zwift as I believe it kills the ability for balance measurement. I guess I was hoping that you had figured out how to pair both pedals and got it working. I tried Ride With GPS and it works pairing both pedals and gives total power so I'm hoping that Urban Biker can get it working fairly easily as I prefer Urban Biker. Thanks for replying.

**Comment by Sublimis** [comment]
Hi, the v7.76 beta version which supports this feature will be out shortly (in about an hour). You can register here, if you haven't already: [https://play.google.com/apps/testing/com.sublimis.urbanbiker](https://play.google.com/apps/testing/com.sublimis.urbanbiker). Let us know how it works!
