### ISSUE TITLE
Distance from Home meter

### ISSUE THREAD

**Issue by azz** [Sublimis/UrbanBiker#95]
Due to COVID our state has imposed a 5km radius in which we are allowed to cycle. Having a sensor that shows you the distance from home (magnitude of vector from starting position to current position) would be fantastic!

Great app, cheers!

**Comment by Sublimis** [comment]
Hi, did you have a chance to try this feature in the latest app release (v5.106)? The feature, i.e. meter mode, is called "Displacement". Thanks for the feedback!

**Comment by azz** [comment]
😱 I just saw this now. You're a gun 💪 Cheers!
