### ISSUE TITLE
Is it possible that something worng in last version that power data is not correctly save?

### ISSUE THREAD

**Issue by radiotbo** [Sublimis/UrbanBiker#99]
In last version the power data from my powermeter is show correctly during the ride and the sensor is detected and connected but when I upload the data to Strava or see the graphs from urban biker track file is bad recorded
![Captura](https://user-images.githubusercontent.com/61949860/93256702-017ab800-f79c-11ea-9c93-824adb956f6b.JPG)

**Comment by zett42** [comment]
Might be related:
https://github.com/Sublimis/UrbanBiker/issues/98

**Comment by radiotbo** [comment]
![IMG_20200927_180719](https://user-images.githubusercontent.com/61949860/94369831-5ac3df00-00ec-11eb-8aeb-7997a1f90f6b.jpg)

**Comment by zett42** [comment]
Try with latest BETA, for me it helped.

**Comment by december-soul** [comment]
Same issue here.
Works fine for a few rides but now the power was not committed to strave correct. Shows just a flat line.

**Comment by radiotbo** [comment]
With last beta deleting the powermeter and linking again seems to work, at least the first ride, i will try again next day

**Comment by radiotbo** [comment]
Today bad info again. During the session seems to be ok, powermeter connected, power and cadence data showed but  the media power value most of the time is 0 and when finish the data showed in the urban biker history is not real and inconsistent with the data showed in strava (urban biker export feature).
![Uploading Screenshot_2020-10-03-18-05-58-347_com.sublimis.urbanbiker.jpg…]()

**Comment by radiotbo** [comment]
![Screenshot_2020-10-03-18-06-20-459_com strava](https://user-images.githubusercontent.com/61949860/94996266-d1a52000-05a3-11eb-8306-f1c2e4c5597c.jpg)

**Comment by radiotbo** [comment]
Last 10 sessions are ok, no more problem with power data or strava. Now using last beta.
